### ISSUE TITLE
Active GW constantly reporting 'Deleted stale gateway' in logs 

### ISSUE THREAD

**Issue by yboaron** [submariner-io/submariner#1912] opened 2022-07-06 12:51 UTC
I first deployed SM on aws ( check [1] for subctl gather info) with a single GW node and then added a second GW (as passive) by running [2] .

Checking the active GW logs after few hours  I can see [3] message appears ~200 times in an hour.

[1] 
[submariner-20220706124154.zip](https://github.com/submariner-io/submariner/files/9054834/submariner-20220706124154.zip)

[2] 

oc label --override nodes ip-10-0-248-107.us-west-1.compute.internal submariner.io/gateway=true

[3] 
W0706 08:10:37.721669      1 syncer.go:174] Deleted stale gateway: ip-10-0-248-107, didn't report for 15s

**Comment by nyechiel** [comment] 2022-07-06 16:02
@yboaron @sridhargaddam any thoughts on what's the severity of this one?

**Comment by sridhargaddam** [comment] 2022-07-07 09:14
To add a second GW for AWS, the recommended procedure is to run "subctl cloud prepare aws --gateways 2 ..."
Any specific reason for using out of bound labelling of the GW node?

**Comment by yboaron** [comment] 2022-07-07 09:22
> To add a second GW for AWS, the recommended procedure is to run "subctl cloud prepare aws --gateways 2 ..." Any specific reason for using out of bound labelling of the GW node?

Nope, just lack of info.
I think I still have the setup, I can check the behavior with 'subctl cloud prepare aws --gateways 2 '.

In the context of adding another GW node, can you please elaborate what 'cloud prepare --gateways 2'  does in addition to labeling the node ?

**Comment by sridhargaddam** [comment] 2022-07-07 10:00
> In the context of adding another GW node, can you please elaborate what 'cloud prepare --gateways 2' does in addition to labelling the node ?

Basically, cloud-prepare configures the prerequisites for Submariner. For a new dedicated GW node, it does the following
1. Spawns a new node using the machineSet API and labels the node as GW node
2. Associates a public-ip on the Gateway node
3. Opens firewall ports UDP/4500 and UDP/4490 for external traffic
4. Opens firewall ports TCP/8080, TCP/8081 and UDP/4480 between all the nodes in the cluster.

**Comment by yboaron** [comment] 2022-07-07 10:56
Thanks for the detailed answer @sridhargaddam 
So, I run the following steps : 
 
1. Removed the label from the node (the one I added as passive)  

`kubectl label nodes <nodename>  submariner.io/gateway-`

2. Restart the single GW pod (by running kubectl delete pod ... )

3. Run cloud prepare for 2 GW 
`subctl cloud prepare aws --gateways 2 --ocp-metadata <metadatafile>
`
 
Still getting the same reports in active pod logs:

W0707 10:53:48.670911       1 syncer.go:174] Deleted stale gateway: ip-10-0-32-51, didn't report for 15s
W0707 10:54:08.764529       1 syncer.go:174] Deleted stale gateway: ip-10-0-32-51, didn't report for 15s
W0707 10:54:28.867568       1 syncer.go:174] Deleted stale gateway: ip-10-0-32-51, didn't report for 15s
W0707 10:54:48.960148       1 syncer.go:174] Deleted stale gateway: ip-10-0-32-51, didn't report for 15s
W0707 10:55:09.052907       1 syncer.go:174] Deleted stale gateway: ip-10-0-32-51, didn't report for 15s
W0707 10:55:29.144715       1 syncer.go:174] Deleted stale gateway: ip-10-0-32-51, didn't report for 15s

**Comment by sridhargaddam** [comment] 2022-07-07 11:25
Basically we have the gatewaySyncer in the submariner-gateway pod which runs periodically (for every 5 secs) and updates the `gateway.submariner.io` object as necessary. Along with this, it also tries to cleanup any stale gateway objects. It looks like there is an issue where it tried to delete which is successful (which is the following log), but it repeats forever (probably some codepath is re-creating it again?) I think @tpantelis knows this code well. Tom, can you please take a look.

``` 
W0707 10:53:48.670911 1 syncer.go:174] Deleted stale gateway: ip-10-0-32-51, didn't report for 15s
```

**Comment by tpantelis** [comment] 2022-07-07 12:02
It prints the warning when `gs.client.Delete(context.TODO(), gw.Name, metav1.DeleteOptions{})` returns no error which means it was successfully deleted. `isGatewayStale` determines if it's stale, ie checks if the `update-timestamp` annotation is out-of-date.

The passive GW should be updating the `update-timestamp` annotation on its `Gateway` resource but it appears this isn't happening. Instead it keeps re-creating it after the active GW deletes it. `syncGatewayStatusSafe` only updates the resource if something in the `Status` has changed, ie `if !reflect.DeepEqual(gatewayObj.Status, existingGw.Status)`. However, since it's passive, the `Status` wouldn't change, hence the `update-timestamp` annotation wouldn't get updated either. It seems we need to either check `update-timestamp` annotation as well or just always update it since we need to update the annotation anyway. I'll see if I can reproduce this scenario in a UT.

**Comment by sridhargaddam** [comment] 2022-07-08 13:38
> @yboaron @sridhargaddam any thoughts on what's the severity of this one?

This does not impact any functionality of Submariner but adds to unnecessary creation/deletion of passive gateway object when more than one gateway is used.

**Comment by tpantelis** [comment] 2022-07-08 13:58
> This does not impact any functionality of Submariner but adds to unnecessary creation/deletion of passive gateway object when more than one gateway is used.

Also this issue wasn't introduced in 0.13 - it's been there all along.

**Comment by nyechiel** [comment] 2022-07-08 14:08
> > This does not impact any functionality of Submariner but adds to unnecessary creation/deletion of passive gateway object when more than one gateway is used.
> 
> Also this issue wasn't introduced in 0.13 - it's been there all along.

I will leave it up to you. If it's an easy fix, I think we should push a PR. If you don't think we need to address it at all, let's just close the issue now.

**Comment by sridhargaddam** [comment] 2022-07-08 14:19
I feel we should fix it.

**Comment by tpantelis** [comment] 2022-07-08 14:54
> I feel we should fix it.

We don’t need to block 0.13 IMO

**Closed as completed** 2022-07-11 08:10 UTC
Labels: bug, backport, 0.13.0-testday
