### ISSUE TITLE
 Submariner connectivity check intermittently failing between managed clusters which are deployed on baremetal 

### ISSUE THREAD

**Issue by aswinsuryan** [submariner-io/submariner#1866] opened 2022-06-09 18:20 UTC
**What happened**:
 Submariner connectivity check intermittently failing between managed clusters which are deployed on baremetal using assisted installer method

The e2e connectivity  tests are failing when the remote pods is on non-gateway node

**What you expected to happen**:
All the tests are expected to pass

**How to reproduce it (as minimally and precisely as possible)**:
Deploy submariner is a cluster with an RHEL node

**Anything else we need to know?**:

The port no in the return traffic seems from the non-gatway node is different from the original port number used and hence the packet is getting dropped

**Environment**:
- Diagnose information (use `subctl diagnose all`):
- Gather information (use `subctl gather`):
- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by aswinsuryan** [comment] 2022-06-10 02:35
The failure logs

[Fail] [dataplane] Basic TCP connectivity tests across clusters without discovery when a pod connects via TCP to a remote pod when the pod is not on a gateway and the remote pod is not on a gateway [It] should have sent the expected data from the pod to the other pod 
github.com/submariner-io/shipyard@v0.12.1/test/e2e/framework/network_pods.go:184

[Fail] [dataplane] Basic TCP connectivity tests across clusters without discovery when a pod connects via TCP to a remote pod when the pod is on a gateway and the remote pod is not on a gateway [It] should have sent the expected data from the pod to the other pod 
github.com/submariner-io/shipyard@v0.12.1/test/e2e/tcp/connectivity.go:71

[Fail] [dataplane] Basic TCP connectivity tests across clusters without discovery when a pod connects via TCP to a remote service when the pod is not on a gateway and the remote service is not on a gateway [It] should have sent the expected data from the pod to the other pod 
github.com/submariner-io/shipyard@v0.12.1/test/e2e/framework/network_pods.go:184

[Fail] [dataplane] Basic TCP connectivity tests across clusters without discovery when a pod connects via TCP to a remote service when the pod is on a gateway and the remote service is not on a gateway [It] should have sent the expected data from the pod to the other pod 
github.com/submariner-io/shipyard@v0.12.1/test/e2e/tcp/connectivity.go:71

[Fail] [dataplane] Basic TCP connectivity tests across clusters without discovery when a pod with HostNetworking connects via TCP to a remote pod when the pod is not on a gateway and the remote pod is not on a gateway [It] should have sent the expected data from the pod to the other pod 
github.com/submariner-io/shipyard@v0.12.1/test/e2e/framework/network_pods.go:184

[Fail] [dataplane] Basic TCP connectivity tests across clusters without discovery when a pod with HostNetworking connects via TCP to a remote pod when the pod is on a gateway and the remote pod is not on a gateway [It] should have sent the expected data from the pod to the other pod 
github.com/submariner-io/shipyard@v0.12.1/test/e2e/framework/network_pods.go:184

Ran 11 of 41 Specs in 466.513 seconds
FAIL! -- 5 Passed | 6 Failed | 0 Pending | 30 Skipped

**Comment by yboaron** [comment] 2022-07-10 07:55
After further investigation, it appears that the root cause was a bug in the kernel [1], nothing to do with Submariner.

@aswinsuryan I think we can close this one, WDYT?

cc @sridhargaddam  


[1]
https://git.kernel.org/pub/scm/linux/kernel/git/netdev/net.git/commit/?id=a82c25c366b0963d33ddf699196e6cf57f6d89b1

**Closed as completed** 2022-07-11 12:36 UTC
Labels: bug
