### ISSUE TITLE
Flakiness in Globalnet E2E

### ISSUE THREAD

**Issue by dfarrell07** [submariner-io/submariner#2420] opened 2023-04-12 17:11 UTC
The [Flake Finder job](https://github.com/submariner-io/submariner/actions?query=workflow%3A%22Flake+Finder%22) has been failing regularly on various Globalnet jobs recently. 

**Non-GN failures:**
1. https://github.com/submariner-io/submariner/actions/runs/4673204750/jobs/8276179533
2. https://github.com/submariner-io/submariner/actions/runs/4751826626/jobs/8441429313?pr=2437

**Globalnet failures:**
I see four types of errors:

1.

>    ✗ Checking if gateway metrics are accessible from non-gateway nodes
   ✗ Unable to access gateway metrics service in submariner-operator namespace: 

(and also, in the same run)

>    ✗ Checking gateway connections
   ✗ Connection to cluster "cluster1" is not established. Connection details:

https://github.com/submariner-io/submariner/actions/runs/4673204750/jobs/8276180472
https://github.com/submariner-io/submariner/actions/runs/4662907724/jobs/8253754982
https://github.com/submariner-io/submariner/actions/runs/4653595540/jobs/8234617771

3.

>    ✗ Checking gateway connections
   ✗ Connection to cluster "cluster1" is not established. Connection details:

(only this error, not the metrics one)

https://github.com/submariner-io/submariner/actions/runs/4624082679/jobs/8178558230
https://github.com/submariner-io/submariner/actions/runs/4662487555/jobs/8252891402
https://github.com/submariner-io/submariner/actions/runs/4613957550/jobs/8156476849

Some runs don't show errors in `diagnose`, just test failures:

4.

> Summarizing 1 Failure:
  [FAIL] [redundancy] Gateway fail-over tests when one gateway node is configured and the submariner gateway pod fails [It] should start a new submariner gateway pod and be able to connect from another cluster
  /go/pkg/mod/github.com/submariner-io/shipyard@v0.15.0-m4/test/e2e/framework/framework.go:561

https://github.com/submariner-io/submariner/actions/runs/4662487555/jobs/8252891585
https://github.com/submariner-io/submariner/actions/runs/4673637880/jobs/8277080537
https://github.com/submariner-io/submariner/actions/runs/4624082679/jobs/8178557925

5.

> Summarizing 1 Failure:
  [FAIL] [dataplane-globalnet] Basic TCP connectivity tests across overlapping clusters without discovery when a pod connects via TCP to the globalIP of a remote service in reverse direction when the pod is not on a gateway and the remote service is not on a gateway [It] should have sent the expected data from the pod to the other pod
  /go/pkg/mod/github.com/submariner-io/shipyard@v0.15.0-m4/test/e2e/framework/network_pods.go:196

https://github.com/submariner-io/submariner/actions/runs/4634160266/jobs/8200087054
https://github.com/submariner-io/submariner/actions/runs/4673637880/jobs/8277080537
https://github.com/submariner-io/submariner/actions/runs/4591595402/jobs/8107887204

This was [discussed some on Slack](https://kubernetes.slack.com/archives/C010RJV694M/p1680797381451939), but to better track the failures over time it's better to collect discussions in an issue.

**Comment by sridhargaddam** [comment] 2023-04-19 18:58
In the following job: https://github.com/submariner-io/submariner/actions/runs/4673637880/jobs/8277080537
**VxLAN/Globalnet:**

The following test failed:
```
Summarizing 1 Failure:
  [FAIL] [dataplane-globalnet] Basic TCP connectivity tests across overlapping clusters without discovery when a pod connects via TCP to the globalIP of a remote service when the pod is not on a gateway and the remote service is not on a gateway [It] should have sent the expected data from the pod to the other pod
```

However, there are no errors in gateway, globalnet, route-agent pods on both the clusters. Also the connections seem to be successfully established.

**Comment by tpantelis** [comment] 2023-04-19 19:03
> However, there are no errors in gateway, globalnet, route-agent pods on both the clusters. Also the connections seem to be successfully established.

yeah I've seen cases of that too. Perhaps it's flakiness in the infra. The only thing is why these issues seem to (mainly) occur with globanet and pretty frequently.

**Comment by sridhargaddam** [comment] 2023-04-19 19:13
In the following job: https://github.com/submariner-io/submariner/actions/runs/4591595402/jobs/8107887204
**Libreswan/Globalnet:**

```
  [FAIL] [dataplane-globalnet] Basic TCP connectivity tests across overlapping clusters without discovery when a pod connects via TCP to the globalIP of a remote service in reverse direction when the pod is not on a gateway and the remote service is not on a gateway [It] should have sent the expected data from the pod to the other pod
```

The connections from cluster1 to cluster2 were not established (health-check failure), but the connections from cluster2 to cluster1 were good. There are no errors in the gateway pod, route-agents. One error is noticed in the globalnet pod on cluster2 where it initially could not find the cniInterfaceIP (as it was waiting for the route-agent to add the annotation), but subsequently after 5 secs it gets notified of the cniInterfaceIP and programs the rules to support healthcheck functionality. This temporary error in Globalnet pod can be ignored as it only affects health-check and the actual datapath validation in `subctl verify ...` should normally pass if the connections were good. Since the test case failed, it mostly implies there was indeed some issue with the connectivity.

```
    "statusMessage": "Failed to successfully ping the remote endpoint IP \"242.254.2.254\"",
```

**Comment by sridhargaddam** [comment] 2023-04-19 19:28
**VxLAN/Globalnet:**

Job: https://github.com/submariner-io/submariner/actions/runs/4662487555/jobs/8252891585

Two datapath tests passed and the third one was the redundancy test-case which was initially (before restarting the GW pod) trying to check the connection status to be successful. However it finds that connection is not established due to the following error.

```
  [FAILED] Failed to await Gateway on "cluster1-worker" with status active and connections UP. Gateway "cluster1-worker" is active but cluster "cluster2" is not connected: Status: "error", Message: "Failed to successfully ping the remote endpoint IP \"242.254.2.254\""
```

Again there are no errors seen in the various submariner pods related to the health-check failure.

-----------------------------------------------------------------------------------------------------------------------------------------------
Job: https://github.com/submariner-io/submariner/actions/runs/4751826626/jobs/8441430301

The first e2e test failed.

```
  [FAIL] [dataplane-globalnet] Basic TCP connectivity tests across overlapping clusters without discovery when a pod with HostNetworking connects via TCP to the globalIP of a remote service when the pod is on a gateway and the remote service is not on a gateway [It] should have sent the expected data from the pod to the other pod
```

No errors in any of the Submariner pods (even health-check was fine).

**Comment by sridhargaddam** [comment] 2023-04-19 19:36
> yeah I've seen cases of that too. Perhaps it's flakiness in the infra. The only thing is why these issues seem to (mainly) occur with globanet and pretty frequently.

Right, the failures are mostly happening on the Globalnet jobs and the current logs are not really helpful :-( 
I tried to reproduce these problems locally by deploying KIND clusters with globalnet followed by running the "subctl verify ..." command multiple times, but it always succeeds on my local host. 

Is there a way to run "subctl gather..." command as part of post-mortem, tar the folder contents and provide a link to download the tar file? 
P.S: It would be preferable to get the tar file rather than dumping the file contents.

**Comment by sridhargaddam** [comment] 2023-04-20 15:08
For the following job failure: https://github.com/submariner-io/submariner/actions/runs/4751826626/jobs/8441429313
**Vanilla SM/Libreswan:**

While the test-case was getting executed, the submariner-gateway pod on cluster2 got restarted, so the shipyard framework which was looking for the active Gateway node (based on the pod labels) could not find the active gateway pod and hence the test failed.

```
• [FAILED] [5.133 seconds]
[dataplane] Basic TCP connectivity tests across clusters without discovery when a pod connects via TCP to a remote pod when the pod is on a gateway and the remote pod is not on a gateway [It] should have sent the expected data from the pod to the other pod
/go/src/github.com/submariner-io/submariner/test/e2e/dataplane/tcp_pod_connectivity.go:36

  [FAILED] Expected
      <int>: 0
  to equal
      <int>: 1
  In [It] at: /go/pkg/mod/github.com/submariner-io/shipyard@v0.15.0-m4/test/e2e/framework/network_pods.go:561 @ 04/20/23 08:01:44.364

  Full Stack Trace
    github.com/submariner-io/shipyard/test/e2e/framework.(*NetworkPod).nodeAffinity(0xc00031fcc0, 0x1)
    	/go/pkg/mod/github.com/submariner-io/shipyard@v0.15.0-m4/test/e2e/framework/network_pods.go:561 +0x226
```

```
 submariner-operator       pod/submariner-gateway-fswvw                         1/1     Running   1 (100s ago)   8m50s   172.18.0.7    cluster2-worker          <none>           <none>
```

This failure can be ignored as the reason for the submariner-gateway pod restart is not known/captured as part of the post-mortem.

**Comment by sridhargaddam** [comment] 2023-05-01 17:22
@dfarrell07 As the necessary fixes have been identified/merged, shall we close this issue?

**Closed as completed** 2023-05-09 13:10 UTC
Labels: bug, priority:high
