### ISSUE TITLE
The exported service cannot be access after the gloablnet enabled

### ISSUE THREAD

**Issue by skeeey** [submariner-io/submariner#1109] opened 2021-01-27 07:33 UTC
**What happened**:

I have there clusters cluster1, cluster2 and cluster3
- cluster1 and cluster2 CIDRs are overlapping
- cluster1 and cluster3 CIDRs are not overlapping

1. I join cluster1 and cluster3 firstly
2. then I join the cluster2
3. after the cluster2 is joined, because the cluster1 and cluster2 CIDRs are overlapping, I will use globalnet, I add the `globalCIDR` for each cluster submariner CR
     - clsuter1: `globalCIDR: 169.254.0.0/19`
     - clsuter2: `globalCIDR: 169.254.32.0/19`
     - cluster3: `globalCIDR: 169.254.64.0/19`

     after I edit the CRs, the submariner pods are restarted and the `submariner-globalnet` pod is created and all clusters are connected

```
CLUSTER ID                    ENDPOINT IP     PUBLIC IP       CABLE DRIVER        TYPE
cluster1                      10.0.32.219     34.219.31.145   libreswan           local
cluster2                      10.0.90.55      3.18.213.213    libreswan           remote
cluster3                      10.0.80.8       54.147.100.113  libreswan           remote

GATEWAY                         CLUSTER                 REMOTE IP       CABLE DRIVER        SUBNETS                                 STATUS
ip-10-0-90-55                   cluster2                10.0.90.55      libreswan           169.254.32.0/19                         connected
ip-10-0-80-8                    cluster3                10.0.80.8       libreswan           169.254.64.0/19                         connected


CLUSTER ID                    ENDPOINT IP     PUBLIC IP       CABLE DRIVER        TYPE
cluster2                      10.0.90.55      3.18.213.213    libreswan           local
cluster1                      10.0.32.219     34.219.31.145   libreswan           remote
cluster3                      10.0.80.8       54.147.100.113  libreswan           remote

GATEWAY                         CLUSTER                 REMOTE IP       CABLE DRIVER        SUBNETS                                 STATUS
ip-10-0-32-219                  cluster1                10.0.32.219     libreswan           169.254.0.0/19                          connected
ip-10-0-80-8                    cluster3                10.0.80.8       libreswan           169.254.64.0/19                         connected

CLUSTER ID                    ENDPOINT IP     PUBLIC IP       CABLE DRIVER        TYPE
cluster3                      10.0.80.8       54.147.100.113  libreswan           local
cluster1                      10.0.32.219     34.219.31.145   libreswan           remote
cluster2                      10.0.90.55      3.18.213.213    libreswan           remote

GATEWAY                         CLUSTER                 REMOTE IP       CABLE DRIVER        SUBNETS                                 STATUS
ip-10-0-32-219                  cluster1                10.0.32.219     libreswan           169.254.0.0/19                          connected
ip-10-0-90-55                   cluster2                10.0.90.55      libreswan           169.254.32.0/19                         connected
```

4. I export the nginx service on each cluster
5. I try to access the nginx service among clusters, but failed, e.g. on cluster1, I try to access the cluster3 service, then I get 
```
curl cluster3.nginx.default.svc.clusterset.local:8080
curl: (28) Failed to connect to cluster3.nginx.default.svc.clusterset.local port 8080: Operation timed out
```
6.  then I restart all of submariner pods with `kubectl -n submariner-operator delete pods --all --grace-period=0 --force` on each cluster
7.  I trey to access the nginx service among clusters again, the service can be accessed

**What you expected to happen**:

I don't need to restart the submariner pods manually

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Submariner version (use `subctl version`): `subctl version: v0.8.0`
- Kubernetes version (use `kubectl version`): `v1.19.0+9f84db3`
- Cloud provider or hardware configuration: AWS/OCP v4.6.4
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug): OpenShiftSDN
- Others:

**Comment by nyechiel** [comment] 2021-01-28 11:11
Thanks for trying Globalnet, @skeeey!

With the original design of Submariner, **all** participating clusters within a clusterset should either use Globalnet or not. It looks like you are trying to mix Globalnet and non-Globalnet which is something we haven't properly tested.

We had some similar request recently, and just added the option to disable Globalnet per cluster with `subctl` (merged now, will be part of 0.9), please refer to https://github.com/submariner-io/submariner-operator/pull/972

Since you are not using `subctl`, I wonder if there is anything we can do to simplify the deployment flow?

/cc @mangelajo @sridhargaddam

**Comment by skeeey** [comment] 2021-01-29 08:18
@nyechiel thanks for your explanation

> With the original design of Submariner, all participating clusters within a clusterset should either use Globalnet or not.

I think this is acceptable, we are collating user use cases, when it is done, I think we can discuss them together.

> It looks like you are trying to mix Globalnet and non-Globalnet which is something we haven't properly tested.

In fact,  I think my purpose is not to mix the Globalnet and non-Globalnet, my purpose is to verify whether the Globalnet can be configured dynamically

My case is:
1. At the beginning, I deploy the broker with `subctl deploy-broker --service-discovery`
2. Then I joined two clusters (cluster1 and cluster3), the two clusters  are not overlapping
     ```
     subctl join broker-info.subm --clusterid cluster1
     subctl join broker-info.subm --clusterid cluster3
     ```
3. Then I joined another cluster (cluster2) with `subctl join broker-info.subm --clusterid cluster2`
4. Because the cluster1 and cluster2 are overlapping, I want to use globalnet to connect all clusters, so I manually added `globalCIDR` to the submariner cr on each cluster with the command `kubectl -n submariner-operator edit submariners.submariner.io submariner`

In the end, all of clusters (cluster1, cluster2 and cluster3) should be in Globalnet, because I added the  `globalCIDR` to them and indeed, I can find the `submariner-globalnet` pod in `submariner-operator` namespace on each cluster

But the problem is the exported service cannot be accessed across clusters, but, as I describe earlier, I try to restart the submariner pods on each cluster, after the pods are restarted, the exported service **can** be accessed across clusters

**Comment by sridhargaddam** [comment] 2021-01-29 11:10
@skeeey I hope you created the nginx-service in each of the clusters after enabling Globalnet in all the clusters. Based on the steps you shared, I see that you probably did it this way, but just want to confirm.

Also, when you tried to curl to the remote nginx service, did you check the IPAddress which got resolved? Does it matches with the globalIP of the remoteService?

**Comment by skeeey** [comment] 2021-02-01 07:14
hi, @sridhargaddam 


I created the nginx-service (only create the nginx deployment and service) in each of the clusters before enabling Globalnet in all the clusters, but I export them after enabling Globalnet in all the clusters

I checked the service IPAddress, I think they match wiht the globallIP, e.g.

```
curl -v cluster2.nginx.default.svc.clusterset.local:8080
*   Trying 169.254.32.75:8080...

curl -v cluster3.nginx.default.svc.clusterset.local:8080
*   Trying 169.254.94.170:8080...
```

**Comment by sridhargaddam** [comment] 2021-02-01 08:13
Thanks, @skeeey. I tried to reproduce the issue using KIND Clusters but it's not reproduced.
However, my clusters are all non-overlapping clusters. I'll see if I can use a similar setup as yours.
Since restarting the Pods fixed your issue, I hope you are not blocked and have a solution to move ahead.
Also as @nyechiel mentioned, ideally it would be great to use `subctl` tool instead of manually updating the submariner CR.


```
bash-5.0# curl cluster3.nginx.default.svc.clusterset.local:8080 --head
HTTP/1.1 200 OK
Server: nginx/1.18.0
Date: Mon, 01 Feb 2021 07:56:05 GMT
Content-Type: text/html
Content-Length: 612
Last-Modified: Thu, 29 Oct 2020 15:23:06 GMT
Connection: keep-alive
ETag: "5f9ade5a-264"
Accept-Ranges: bytes
```

**Comment by skeeey** [comment] 2021-02-01 10:28
@sridhargaddam yes, this is not a blocked issue for me :)

I try to use `subctl` to set globalnet, I got a warning message
```
Globalnet is not enabled on Broker. Ignoring specified globalnet-cidr
``` 
this because I did not specify the `--globalnet` when I deployed the broker, the `globalnetEnabled` is false in configmap `submariner-k8s-broker/submariner-globalnet-info`

and I go through the code, I found it seems that the `submariner-globalnet-info` cm is only used by  `subctl`, am I right?
or the `submariner-globalnet-info` cm is required when we enable the `gglobalnet`?

**Comment by mangelajo** [comment] 2021-02-01 10:33
Just one side note on the conversation: About the order of configuration, or resource creation. It should be irrelevant. The system status should converge on the declared configuration eventually. The order in which we make the configurations shall be irrelevant. If there is order dependence there are corner cases we are not addressing in the code and we should.

**Comment by nyechiel** [comment] 2021-02-24 15:43
Hi @skeeey - do you need more help with this Issue?

**Comment by skeeey** [comment] 2021-02-25 02:14
@nyechiel , because there is a workaround for this, this is not urgent for me, I think this is a low priority issue, thanks

**Comment by nyechiel** [comment] 2021-03-03 16:01
Closing this one for now. Please reopen when/if it's relevant again.

**Closed by nyechiel** 2021-03-03 16:01 UTC
Labels: bug, globalnet
