### ISSUE TITLE
Sometimes remote endpoint RTT is reported as '0'

### ISSUE THREAD

**Issue by yboaron** [submariner-io/submariner#1857] opened 2022-05-31 16:29 UTC
I have deployed SM clustersset with GN on aws, gcp and azure, and sometimes RTT is reported as '0 'even though the endpoint is successfully connected and round trip is ~70mSec.

The following error is reported in GW crd [1] while I can ping manually the remote endpoint [2].

Restarting the gw pod solved the problem.
Attached is GW's pod log [gwpod.txt](https://github.com/submariner-io/submariner/files/8807027/gwpod.txt)

[1]
status:
  connections:
  - endpoint:
      backend: libreswan
      backend_config:
        natt-discovery-port: "4490"
        preferred-server: "true"
        preferred-server-timestamp: "1654000314"
        udp-port: "4500"
        using-loadbalancer: "true"
      cable_name: submariner-cable-gcp-a-10-0-128-2
      cluster_id: gcp-a
      healthCheckIP: 242.2.255.254
      hostname: yblb-7sv57-worker-b-7h5tq.c.gc-acm-dev.internal
      nat_enabled: true
      private_ip: 10.0.128.2
      public_ip: 34.148.193.38
      subnets:
      - 242.2.0.0/16
    latencyRTT:
      average: 0s
      last: 0s
      max: 0s
      min: 0s
      stdDev: 0s
    status: connected
    statusMessage: 'Failed to run the pinger for the remote endpoint IP "242.2.255.254":
      write ip4 0.0.0.0->242.2.255.254: sendto: object is remote'
    usingIP: 34.148.193.38
    usingNAT: true

[2]

sh-4.4# ping 242.2.255.254
PING 242.2.255.254 (242.2.255.254) 56(84) bytes of data.
64 bytes from 242.2.255.254: icmp_seq=1 ttl=64 time=71.5 ms
64 bytes from 242.2.255.254: icmp_seq=2 ttl=64 time=71.3 ms
64 bytes from 242.2.255.254: icmp_seq=3 ttl=64 time=71.3 ms

**Comment by lonelyCZ** [comment] 2022-06-09 07:50
I also encountered this issue after my hosts was restarted.

**Comment by sridhargaddam** [comment] 2022-06-09 11:22
> I also encountered this issue after my hosts was restarted.

Did you notice this in Globalnet or non Globalnet deployments?

**Comment by lonelyCZ** [comment] 2022-06-10 01:55
> Did you notice this in Globalnet or non Globalnet deployments?

I deploy it in Globalnet. I found the time of my hosts were not sync, my `Submariner` has been recovered when I resync time and restart its all pods.

**Comment by nyechiel** [comment] 2022-06-14 10:57
@yboaron @sridhargaddam how urgent this issue is? are we ok with pushing it out from 0.13?

**Comment by yboaron** [comment] 2022-06-14 11:26
> @yboaron @sridhargaddam how urgent this issue is? are we ok with pushing it out from 0.13?

I don't think it's urgent and we have a workaround to handle this issue. 
+1 for pushing it out from 0.13

**Comment by sridhargaddam** [comment] 2022-06-14 14:23
> > @yboaron @sridhargaddam how urgent this issue is? are we ok with pushing it out from 0.13?
> 
> I don't think it's urgent and we have a workaround to handle this issue. +1 for pushing it out from 0.13

+1 to moving it out of 0.13

**Comment by nyechiel** [comment] 2022-06-30 18:33
@sridhargaddam @yboaron I will wait for your recommendation on whether or not we want to get this into 0.13. I have seen the issue quite often myself, but I am not sure if the proposed PR is addressing the root cause.

**Closed as completed** 2022-07-04 09:34 UTC
Labels: bug, datapath, backport
