### ISSUE TITLE
The cluster is deployed with kube-proxy ipvs mode which Submariner does not support

### ISSUE THREAD

**Issue by 13567436138** [submariner-io/submariner#1559] opened 2021-09-24 03:00 UTC
✗ Checking Submariner support for the kube-proxy mode 
 ✗ The cluster is deployed with kube-proxy ipvs mode which Submariner does not support

**Comment by jinglina** [comment] 2021-10-25 01:53
same question with you

**Comment by dfarrell07** [comment] 2021-12-21 14:57
It seems to me like this is a duplicate of https://github.com/submariner-io/submariner/issues/1611. Can we handle discussion there?

**Closed as completed by dfarrell07** 2021-12-21 14:57 UTC
