### ISSUE TITLE
Rename all "Netshoot" names to "Nettest"

### ISSUE THREAD

**Issue by manosnoam** [submariner-io/submariner#956] opened 2020-11-22 13:29 UTC
Since the recent change in [Docker Hub Image Retention Policy](https://www.docker.com/blog/docker-hub-image-retention-policy-delayed-and-subscription-updates/), running [Netshoot](https://github.com/nicolaka/netshoot) pod may fail on ImagePullBackOff, with message:

`Failed to pull image "nicolaka/netshoot": rpc error: code = Unknown desc = Error reading manifest latest in docker.io/nicolaka/netshoot: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit`

In submariner-io there're still many referrals to the "Netshoot" name, in several repositories:
https://github.com/search?q=org%3Asubmariner-io+netshoot&type=code

For example:
https://github.com/submariner-io/shipyard/blob/master/scripts/shared/resources/netshoot.yaml

Since the original Netshoot image is not part of CI anymore - as it was replaced with "quay.io/submariner/nettest" - 
it should also be referred as "Nettest" anywhere, to avoid confusion.

**Comment by mkolesnik** [comment] 2020-11-22 13:34
I suggest we close this as it's not a bug.

The name is just a name which is used internally and has no significance. The actual image we use is an internal image which is not hosted on docker hub.

> Since the recent change in [Docker Hub Image Retention Policy](https://www.docker.com/blog/docker-hub-image-retention-policy-delayed-and-subscription-updates/), running [Netshoot](https://github.com/nicolaka/netshoot) pod may fail on ImagePullBackOff, with message:
> 
> `Failed to pull image "nicolaka/netshoot": rpc error: code = Unknown desc = Error reading manifest latest in docker.io/nicolaka/netshoot: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit`

Where has this happened? Have you a link to a job that failed this way?

**Comment by manosnoam** [comment] 2020-11-22 16:53
> Where has this happened? Have you a link to a job that failed this way?

This error started to happen on my env [recently](https://qe-jenkins-csb-skynet.cloud.paas.psi.redhat.com/job/Submariner-OSP-AWS-Globalnet/16/Test-Report/), since I still use `nicolaka/netshoot` (which is the original image we had for Submariner tests). 

For those who're familiar with Netshoot, it might be good to understand that the image for testing is not Netshoot anymore, but a new one - [Nettest](https://quay.io/repository/submariner/nettest) (that is missing description by the way).
 
+@nyechiel, +@mangelajo

**Comment by nyechiel** [comment] 2020-11-30 07:33
@manosnoam I tend to agree with Mike here. Users should not really care about the name of the image. Yes, we can clean/replace the name in a couple of places, but it's not going to impact any user experience or even be visible for a typical user. I also reviewed the Submariner website and I don't see any reference to netshoot, see for e.g https://submariner.io/getting_started/quickstart/kind/#verify

**Comment by manosnoam** [comment] 2020-11-30 11:58
@nyechiel,
Folks who followed the instructions to test Submariner, might hit same issue as described in #369, where using Docker images for testing Submariner, may fail due to requests rate limit. This is how I found out that Netshoot should not be used for daily tests.

Our tests should refer to the correct image name, here're concrete examples of confusing naming:

These configurations/scripts are not using Netshoot anymore:
- `scripts/shared/resources/netshoot.yaml`
- `test/scripts/post_mortem/test.sh`


These E2E tests are not using Netshoot either, but ginkgo descriptions refers to it as Netshoot:
- `test/e2e/discovery/headless_services.go`
- `test/e2e/discovery/statefulsets.go`

More examples:
https://github.com/search?q=org%3Asubmariner-io+netshoot&type=code

**Comment by Jaanki** [comment] 2020-12-23 06:09
I think we shouldn't change the name to nettest. The image references are changed to "nettest" everywhere which is what matters. nettest image still provides netshoot app and hence the name should be kept to netshoot and not changed.

**Closed** 2020-12-23 06:12 UTC
Labels: bug, docs
