### ISSUE TITLE
Submariner not working on premise K8s-clusters

### ISSUE THREAD

**Issue by engrzain** [submariner-io/submariner#2658] opened 2023-08-24 11:07 UTC
Hi, I have installed submariner on two k8-cluster on premises cni flannel. 
On both the sides when i checked status using **subctl show all**  it gives error status.
I am attaching subctl gather from the both cluster. Can someone please point out whats the issue. I have checked two version 0.14.6 and 0.15.2 and error on both version are same. These logs are from 0.14.6

[submariner-20230824104601.tar.gz](https://github.com/submariner-io/submariner/files/12428684/submariner-20230824104601.tar.gz)

[submariner-20230824104725.tar.gz](https://github.com/submariner-io/submariner/files/12428685/submariner-20230824104725.tar.gz)

**Comment by sridhargaddam** [comment] 2023-08-25 06:48
@engrzain looks like both the attachments are empty.

**Comment by engrzain** [comment] 2023-08-25 06:50
Please have a look again.

[submariner-20230824104601.tar.gz](https://github.com/submariner-io/submariner/files/12436383/submariner-20230824104601.tar.gz)
[submariner-20230824104725.tar.gz](https://github.com/submariner-io/submariner/files/12436387/submariner-20230824104725.tar.gz)

**Comment by sridhargaddam** [comment] 2023-08-25 17:29
The issue was that ESP traffic was not allowed between the cluster Gateway nodes. Hence, connections could not be established. It was confirmed that after moving to VxLAN cable-driver the connections are all good.

This was discussed on slack - https://kubernetes.slack.com/archives/C010RJV694M/p1692948447566799?thread_ts=1692705479.341019&cid=C010RJV694M

**Closed as completed by sridhargaddam** 2023-08-25 17:29 UTC
Labels: support

**Comment by engrzain** [comment] 2023-08-26 08:44
Thanks @sridhargaddam for your assistance.
