### ISSUE TITLE
Broken service connectivity across cluster with ovn-kubernetes

### ISSUE THREAD

**Issue by luis5tb** [submariner-io/submariner#1608] opened 2021-12-03 16:51 UTC
**What happened**:
Exposed services are not reachable from remote cluster when using ovn-kubernetes (in a OKD 4.9 environment). 

The clusters are properly connected and the services are properly exported. The traffic reaches the remote gateway and it gets inyected into br-submariner ovs bridge as expected, however the traffic gets dropped there (I check the geneve tunnel between the gateway node and the node hosting the service pod does not have any traffic).

Checking further, it was observed that the loadbalancer is not associated to the submariner router at the OVN NB DB:
ovn-nbctl lr-lb-list SUBMARINER_ROUTER_ID
(empty return)

If the loadbalancer id get gets manually added to the submariner router (lr-lb-add SUBMARINER_ROUTER_ID LOADBALANCER_ID) then the connectivity works as expected

 **What you expected to happen**:
Connectivity to work out of the box

**How to reproduce it (as minimally and precisely as possible)**:
Deploy 2 clusters witn ovn-kubernetes, expose a service in one of them, trying to reach it from the other.

**Anything else we need to know?**:
I deployed with OKD and saw that the next function seems to look for something into the external_ids to find the loadbalancers to attach to the submariner router: https://github.com/submariner-io/submariner/blob/devel/pkg/networkplugin-syncer/handlers/ovn/services.go#L56,
so I'm not sure if this is related to how those external ids are handle in this type of environment or would happen the same in any environment using ovn-kubernetes

**Environment**:
- Diagnose information (use `subctl diagnose all`):
All green here

- Gather information (use `subctl gather`):
- Cloud provider or hardware configuration:
Environment is running in VMs in a cloud provider (OpenStack based)

- Install tools:
Using okd IPI installer for the k8s cluster.

- Others:

**Comment by astoycos** [comment] 2022-01-12 19:26
I'd like to look into fixing this one!

**Comment by astoycos** [comment] 2022-01-12 20:13
So I was able to reproduce this exact scenario locally, specifically the Loadbalancer created for a given service (in this case `nginx-demo`) is not properly added to the `submariner-router` 

```
_uuid               : 78f7675e-e9c2-4150-a704-f45a9e75b449
external_ids        : {"k8s.ovn.org/kind"=Service, "k8s.ovn.org/owner"="default/nginx-demo"}
health_check        : []
ip_port_mappings    : {}
name                : "Service_default/nginx-demo_TCP_cluster"
options             : {event="false", reject="true", skip_snat="false"}
protocol            : tcp
selection_fields    : []
vips                : {"100.1.99.189:80"="10.1.0.6:8080,10.1.1.5:8080"}
```
```
[root@cluster1-control-plane ~]# ovn-nbctl find logical_router name=submariner_router
_uuid               : 885c3960-19b3-43d2-8440-6e082e0a45a7
copp                : []
enabled             : []
external_ids        : {}
load_balancer       : []
load_balancer_group : []
name                : submariner_router
nat                 : []
options             : {chassis="bd28702d-7292-4b4a-a674-6669147d3f00"}
policies            : []
ports               : [20e10480-7860-4f7c-976a-6cb4c9f43b0c, fb57d1f3-b5ca-442b-9ff9-b03eb358b64f]
static_routes       : [04714627-b33d-46e3-a973-daed65b1f0c1, a191b661-092f-4475-9527-589b24ad6d6b, a9ca39a5-014f-4840-9b40-1fd78dee9f67, b787a8db-1299-4cb3-950e-6414d0de7274]
```

Manually adding the load balancer `ovn-nbctl lr-lb-add submariner_router 78f7675e-e9c2-4150-a704-f45a9e75b449` fixes the issue.  This issue arose because of a major design change within OVN-K that standardized the way loadbalancers are made and assigned to Routers/Switches. More details can be found in that original PR https://github.com/ovn-org/ovn-kubernetes/pull/2294

**Comment by astoycos** [comment] 2022-01-13 15:49
@astoycos (Mentioning myself since I'm not a contributor and can't assign it)

**Comment by dfarrell07** [comment] 2022-05-24 13:42
This should be helped by https://github.com/submariner-io/submariner/pull/1689, which is almost ready to merge.

**Closed as completed** 2022-06-04 12:27 UTC
Labels: bug, OVN
