### ISSUE TITLE
Building submariner repos (shipyard, submariner, operator) fails for missing scripts/lib

### ISSUE THREAD

**Issue by manosnoam** [submariner-io/submariner#576] opened 2020-05-19 05:48 UTC
Building submariner repo failed on:

./scripts/build
./scripts/build: line 5: /lib/debug_functions: No such file or directory

**Comment by sridhargaddam** [comment] 2020-05-19 08:10
@mangelajo @skitt @mkolesnik ^^

**Comment by skitt** [comment] 2020-05-19 08:18
You need to set `SCRIPTS_DIR` to point to Shipyard, for example

     SCRIPTS_DIR=${GOPATH}/src/github/submariner-io/shipyard/scripts/shared ./scripts/build

**Comment by manosnoam** [comment] 2020-05-19 09:38
For this repo, I have run:
`SCRIPTS_DIR=./scripts/lib ./scripts/build`

Perhaps we should document it (in Website), for those who want to build without dapper ?

**Comment by skitt** [comment] 2020-05-19 10:33
We’ve said several times that we don’t want to explicitly support people building without Dapper...

**Comment by skitt** [comment] 2020-05-19 13:40
> For this repo, I have run:
> `SCRIPTS_DIR=./scripts ./scripts/build`

I gave you the exact command to use, why not use it?

**Comment by mangelajo** [comment] 2020-05-20 08:07
We cannot support people building outside of dapper, if the issue is not having docker on the CI hosts I think we need to work with them to enable it.

Also, including all the e2e functionality in subctl would help fix this dependency. I'm closing this bug on favor of that. But feel free to reopen if you believe that won't fix your need.

**Closed by mangelajo** 2020-05-20 08:07 UTC
Labels: bug, wontfix
