### ISSUE TITLE
Submariner "Deploy kind+Submariner Locally" Breaks on Fedora

### ISSUE THREAD

**Issue by pinikomarov** [submariner-io/submariner#933] opened 2020-11-10 11:53 UTC
On Fedora 32/33 if you folllow the submariner quickstart guide, you'll hit these two issues: 

clone repo, 
after "make deploy":

1) docker: Got permission denied while trying to connect to the Docker daemon socket
solved by:

        $ sudo usermod -aG docker your-user

then logoff

2) docker: Error response from daemon: OCI runtime create failed: this version of runc doesn't work on cgroups v2
[solved by](https://docs.docker.com/engine/install/fedora/#installation-methods):

        $ sudo grubby --update-kernel=ALL --args="systemd.unified_cgroup_hierarchy=0"

then reboot

The guide does say that "Docker must be installed" 
BUT initial failures without warnings my defer potential users, since the solutions to the failures mentioned are non trivial and require logoff and or reboot they should be adressed on our side by one of two ways : 
- via documentation : add an *issues for fedora users
that specify those exact two issues and the way to resolve them
- on submariner deploy side : add a warning that if this is a fedora OS , then a check will be made for grub and user groups when running make deploy .

**Comment by pinikomarov** [comment] 2020-11-10 11:54
@mkolesnik @nyechiel WDYT ?

**Comment by nyechiel** [comment] 2020-11-10 12:00
Hi @pinikomarov. Thanks for reporting this. These are "known issues" with Fedora and Docker. I don't think there is much we can do about it on the Submariner side. You should also bear in mind that the quickstart is not specific to Fedora, and users can follow it with Mac or Windows.. so it needs to be generic enough yet working :)

**Comment by pinikomarov** [comment] 2020-11-10 13:19
did any of the mac or ubuntu users report this issues ? 
(I know ubuntu did not since I tested on it)
I'm just saying that an asterix for fedora users is easy to do and goes a long way for newbe users

**Comment by nyechiel** [comment] 2020-11-10 13:23
> did any of the mac or ubuntu users report this issues ?
> (I know ubuntu did not since I tested on it)
> I'm just saying that an asterix for fedora users is easy to do and goes a long way for newbe users

No, the issue is specific to Fedora. Starting with Fedora 32, Fedora uses alternatives to Docker, like Podman and Buildah. @dfarrell07 what's you opinion on this?

**Comment by dfarrell07** [comment] 2020-11-10 18:41
I generally think we should try to avoid documenting details that aren't about Submariner. I think this is pretty fundamental to Docker use on Fedora 32.

We currently have the note "Docker must be installed and running on your computer". If I were to test that, I might run something like `docker run --rm alpine sh -c 'wget -q -O- http://docs.docker.com | grep "<title"'` and see that network connectivity in the container fails. That wouldn't have anything to do with Submariner, only the Docker install.

I also think it's pretty unlikely that there will be many folks who 1) Use Fedora 32+ and 2) First use Docker in that environment while trying Submariner.

**Comment by nyechiel** [comment] 2020-11-11 07:12
@pinikomarov I am going to close this. The current note says that "Docker must be installed and running on your computer" before you do anything with Submariner which is accurate. I don't think we should document OS-specific issues and caveats.

**Closed by nyechiel** 2020-11-11 07:12 UTC

**Comment by pinikomarov** [comment] 2020-11-11 08:40
ok
