### ISSUE TITLE
Submariner failing on EKS

### ISSUE THREAD

**Issue by shinji62** [submariner-io/submariner#2917] opened 2024-02-20 07:22 UTC
**What happened**:
I tried submariner across two EKS cluster (overlapping CIDR) , on different region / different VPC (not peered)

Application use headless service, I can see that serviceexporter and serviceimporter are created and application domain resolve to global ip 212... but the connection doesn t work, just timeout. I can see that both cluster are connected using the show command, so both node GW can communicate.

**What you expected to happen**:
Would expect that my service can be reach from both cluster, using the `clusterset` service.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
diagnose all
```shell
✓ Checking Submariner support for the Kubernetes version
 ✓ Kubernetes version "v1.27.9-eks-5e0fdde" is supported
 ✗ Globalnet deployment detected - checking that globalnet CIDRs do not overlap
 ✗ Error getting the Broker's REST config: error getting auth rest config: Get "https://clusterIDDgr7.ap-northeast-1.eks.amazonaws.com/apis/submariner.io/v1/namespaces/submariner-k8s-broker/clusters/any": tls: failed to verify certificate: x509: “kube-apiserver” certificate is not trusted
 ⚠ Checking Submariner support for the CNI network plugin
 ⚠ Submariner could not detect the CNI network plugin and is using ("generic") plugin. It may or may not work.
 ✓ Checking gateway connections
 ✓ Checking Submariner support for the kube-proxy mode
 ✓ The kube-proxy mode is supported
 ✓ Checking that firewall configuration allows intra-cluster VXLAN traffic
 ✓ Checking that Globalnet is correctly configured and functioning
 ✓ Checking that services have been exported properly
 ✓ Checking Submariner support for the Kubernetes version
 ✓ Kubernetes version "v1.27.9-eks-5e0fdde" is supported
 ✗ Globalnet deployment detected - checking that globalnet CIDRs do not overlap
 ✗ Error getting the Broker's REST config: error getting auth rest config: Get "https://clusterid.gr7.ap-northeast-1.eks.amazonaws.com/apis/submariner.io/v1/namespaces/submariner-k8s-broker/clusters/any": tls: failed to verify certificate: x509: “kube-apiserver” certificate is not trusted
 ⚠ Checking Submariner support for the CNI network plugin
 ⚠ Submariner could not detect the CNI network plugin and is using ("generic") plugin. It may or may not work.
 ✓ Checking gateway connections
 ✓ Checking Submariner support for the kube-proxy mode
 ✓ The kube-proxy mode is supported
 ✓ Checking that firewall configuration allows intra-cluster VXLAN traffic
 ✗ Checking that Globalnet is correctly configured and functioning
 ✗ No matching GlobalIngressIP resource found for exported service "default/nginx"
 ✓ Checking that services have been exported properly

subctl version: v0.16.3
```

[submariner.tgz](https://github.com/submariner-io/submariner/files/14340825/submariner.tgz)

**Comment by yboaron** [comment] 2024-02-20 09:06
A. I checked the logs , looks fine, didn't find any errors. 

B. Does subctl verify consistently fail only for use case [1]  (**pod is not on a gateway and the remote service is not on a gateway**) ?  


[1] 
[dataplane-globalnet] Basic TCP connectivity tests across overlapping clusters without discovery when a pod connects via TCP to the globalIP of a remote service when the pod is not on a gateway and the remote service is not on a gateway should have sent the expected data from the pod to the other pod

**Comment by shinji62** [comment] 2024-02-21 00:30
Yes @yboaron it failed for the case where `pod is not on a gateway and the remote service is not on a gateway`.

**Comment by yboaron** [comment] 2024-02-21 09:49
> it failed for the case where pod is not on a gateway and the remote service is not on a gateway.

1. It implies some datapath issue when both client pod and remote service pod run on non gw node,
   Submariner inter-cluster traffic is asymmetric, egress handled by Submariner and ingress by the CNI.

   So the datapath for pod@non_gwnode_cluster1 to pod@non_gwnode_cluster2 comprise of the following segments:

A. pod@non_gwnode_cluster1 to GWnode@cluster1 using Submariner intra-cluster VxLAN tunnel
B. SNAT (for GlobalNet in your case)
C.  Inter-cluster VxLAN/IPSec tunnel
D. CNI handles RX from GWnode@cluster2 to pod@nonGWnode_cluster2

   You can find more details about submariner datapath [here](https://github.com/submariner-io/submariner/issues/2541#issuecomment-1584438003)

2.  Can you please check that submariner [prerequisites](https://submariner.io/getting-started/#prerequisites) for intra-cluster traffic  are allowed , you can use **subctl diagnose firewall intra-cluster --kubeconfig <kubeconfig_file>** command

3. Also, you can check if some infra/platform security group blocking submariner intra-cluster traffic (VxLAN, udp port 4800)
4. Last step, we can tcpdump the relevant nodes and see where the traffic is dropped,   it can help understand the root cause

**Comment by shinji62** [comment] 2024-02-22 05:28
Ok I guess could be because the k8S node are on the same CIDR that the pod according to `Worker node IPs on all connected clusters must be outside of the Pod/Service CIDR ranges.`

**Comment by yboaron** [comment] 2024-02-22 13:05
> Ok I guess could be because the k8S node are on the same CIDR that the pod according to `Worker node IPs on all connected clusters must be outside of the Pod/Service CIDR ranges.`

Yep, can you try with node IPs not overlap with pod/service CIDRs ?

**Comment by shinji62** [comment] 2024-02-26 04:57
@yboaron I try with non overlapping CIDR, but still the same issue remains.

**Comment by yboaron** [comment] 2024-03-03 13:01
A. Can you please check that submariner [prerequisites](https://submariner.io/getting-started/#prerequisites) for intra-cluster traffic are allowed ? , you can use **subctl diagnose firewall intra-cluster --kubeconfig <kubeconfig_file>** command


if A looks OK, we can tcpdump the relevant nodes and see where the traffic is dropped

**Comment by dfarrell07** [comment] 2024-04-02 13:03
Closing for now, feel free to reopen if this is still relevant.

**Closed as completed by dfarrell07** 2024-04-02 13:03 UTC
Labels: bug, enhancement
