### ISSUE TITLE
Submariner v0.16.3 Gateway Pods are stuck in a Container-creating state while the OCP upgrade to 4.15 on Site 1

### ISSUE THREAD

**Issue by BhavaniYalamanchili** [submariner-io/submariner#2955] opened 2024-04-01 08:17 UTC
### **ISSUE:**
When we started the upgrade of OCP on Site 1 from 4.14 to 4.15, we found that the submariner connectivity was down and the gateway pods on Site1 were stuck in Container-creating state

### **SETUP:**
Site 1: OCP 4.14 - upgrade in progress to 4.15
Site 2: OCP 4.14
Submariner: v0.16.3

### **Outputs of Show and Diagnose all commands**
From Site 2

Show all for Site2

```
sh-4.4$ /root/.local/bin/subctl show all --kubeconfig /tmp/local-kubeconfig 
Cluster "local-config"
 ✓ Detecting broker(s)
 ✓ No brokers found

 ✓ Showing Connections
GATEWAY                          CLUSTER   REMOTE IP       NAT   CABLE DRIVER   SUBNETS                        STATUS       RTT avg.     
control-1-ru4.rackae1.mydomain   site1     172.20.200.27   no    libreswan      172.30.0.0/16, 10.128.0.0/14   connecting   350.941µs    

 ✓ Showing Endpoints
CLUSTER   ENDPOINT IP     PUBLIC IP     CABLE DRIVER   TYPE     
site2     172.20.102.25   129.41.87.3   libreswan      local    
site2     172.20.102.26   129.41.87.3   libreswan      local    
site1     172.20.200.27   129.41.87.2   libreswan      remote   
site2     172.20.102.27   129.41.87.3   libreswan      local    

 ✓ Showing Gateways
NODE                             HA STATUS   SUMMARY                                  
control-1-ru2.rackae2.mydomain   passive     There are no connections                 
control-1-ru3.rackae2.mydomain   active      0 connections out of 1 are established   
control-1-ru4.rackae2.mydomain   passive     There are no connections                 

 ✓ Showing Network details
    Discovered network details via Submariner:
        Network plugin:  OVNKubernetes
        Service CIDRs:   [172.31.0.0/16]
        Cluster CIDRs:   [10.132.0.0/14]

 ✓ Showing versions 
COMPONENT                       REPOSITORY           CONFIGURED   RUNNING                     ARCH    
submariner-gateway              quay.io/submariner   0.16.3       release-0.16-58e6b641a736   amd64   
submariner-routeagent           quay.io/submariner   0.16.3       release-0.16-58e6b641a736   amd64   
submariner-metrics-proxy        quay.io/submariner   0.16.3       release-0.16-03f30315107e   amd64   
submariner-operator             quay.io/submariner   0.16.3       release-0.16-133b18e07a09   amd64   
submariner-lighthouse-agent     quay.io/submariner   0.16.3       release-0.16-487f6296ce9b   amd64   
submariner-lighthouse-coredns   quay.io/submariner   0.16.3       release-0.16-487f6296ce9b   amd64   
```

Show all for Site1

```
sh-4.4$ /root/.local/bin/subctl show all --kubeconfig /connection/kube-config/71a5f5abfc/kubeconfig 
Cluster "default-cluster"
 ✓ Detecting broker(s)
NAMESPACE               NAME                COMPONENTS                        GLOBALNET   GLOBALNET CIDR   DEFAULT GLOBALNET SIZE   DEFAULT DOMAINS   
submariner-k8s-broker   submariner-broker   service-discovery, connectivity   no          242.0.0.0/8      65536                                      

 ✓ Showing Connections
GATEWAY                          CLUSTER   REMOTE IP       NAT   CABLE DRIVER   SUBNETS                        STATUS       RTT avg.     
control-1-ru3.rackae2.mydomain   site2     172.20.102.26   no    libreswan      172.31.0.0/16, 10.132.0.0/14   connecting   3.371184ms   

 ✓ Showing Endpoints
CLUSTER   ENDPOINT IP     PUBLIC IP     CABLE DRIVER   TYPE     
site1     172.20.200.25   129.41.87.2   libreswan      local    
site2     172.20.102.26   129.41.87.3   libreswan      remote   

 ✓ Showing Gateways
NODE                             HA STATUS   SUMMARY                                  
control-1-ru2.rackae1.mydomain   active      0 connections out of 1 are established   

 ✓ Showing Network details
    Discovered network details via Submariner:
        Network plugin:  OVNKubernetes
        Service CIDRs:   [172.30.0.0/16]
        Cluster CIDRs:   [10.128.0.0/14]

 ✓ Showing versions 
COMPONENT                       REPOSITORY           CONFIGURED   RUNNING                     ARCH    
submariner-gateway              quay.io/submariner   0.16.3       release-0.16-58e6b641a736   amd64   
submariner-routeagent           quay.io/submariner   0.16.3       release-0.16-58e6b641a736   amd64   
submariner-metrics-proxy        quay.io/submariner   0.16.3       release-0.16-03f30315107e   amd64   
submariner-operator             quay.io/submariner   0.16.3       release-0.16-133b18e07a09   amd64   
submariner-lighthouse-agent     quay.io/submariner   0.16.3       release-0.16-487f6296ce9b   amd64   
submariner-lighthouse-coredns   quay.io/submariner   0.16.3       release-0.16-487f6296ce9b   amd64   
```

Diagnose all for Site 2

```
sh-4.4$ /root/.local/bin/subctl diagnose all --kubeconfig /tmp/local-kubeconfig 
Cluster "local-config"
 ✓ Checking Submariner support for the Kubernetes version
 ✓ Kubernetes version "v1.27.11+d8e449a" is supported

 ✗ Non-Globalnet deployment detected - checking that cluster CIDRs do not overlap 
 ✗ Error getting the Broker's REST config: error getting auth rest config: Unauthorized

 ✓ Checking Submariner support for the CNI network plugin
 ✓ The detected CNI network plugin ("OVNKubernetes") is supported
 ✓ Checking OVN version 
 ✓ The ovn-nb database version 7.1.0 is supported
 ✗ Checking gateway connections
 ✗ Connection to cluster "site1" is in progress
 ✓ Checking Submariner support for the kube-proxy mode
 ✓ Cluster is running with "OVNKubernetes" CNI which internally implements kube-proxy functionality
 ✓ Checking that firewall configuration allows intra-cluster VXLAN traffic

 ✓ Checking that services have been exported properly

Skipping inter-cluster firewall check as it requires two kubeconfigs. Please run "subctl diagnose firewall inter-cluster" command manually.

subctl version: v0.16.3
```

Diagnose all for Site 1

```
sh-4.4$ /root/.local/bin/subctl diagnose all --kubeconfig /connection/kube-config/71a5f5abfc/kubeconfig 
Cluster "default-cluster"
 ✓ Checking Submariner support for the Kubernetes version
 ✓ Kubernetes version "v1.28.7+f1b5f6c" is supported

 ✗ Non-Globalnet deployment detected - checking that cluster CIDRs do not overlap 
 ✗ Error getting the Broker's REST config: error getting auth rest config: Unauthorized

 ✓ Checking Submariner support for the CNI network plugin
 ✓ The detected CNI network plugin ("OVNKubernetes") is supported
 ✓ Checking OVN version 
 ✓ The ovn-nb database version 7.1.0 is supported
 ✗ Checking gateway connections
 ✗ Connection to cluster "site2" is in progress
 ✓ Checking Submariner support for the kube-proxy mode
 ✓ Cluster is running with "OVNKubernetes" CNI which internally implements kube-proxy functionality
 ✓ Checking that firewall configuration allows intra-cluster VXLAN traffic

 ✓ Checking that services have been exported properly

Skipping inter-cluster firewall check as it requires two kubeconfigs. Please run "subctl diagnose firewall inter-cluster" command manually.

subctl version: v0.16.3
```

### **Subctl Gather logs**

Please change the the extension to zip when downloaded

[From Site1-Site1 logs.txt](https://github.com/submariner-io/submariner/files/14820501/Site1-1.txt)
[From Site1-Site2 logs.txt](https://github.com/submariner-io/submariner/files/14820502/Site1-2.txt)
[From Site2-Site1 logs.txt](https://github.com/submariner-io/submariner/files/14820505/Site2-1.txt)
[From Site2-Site2 logs.txt](https://github.com/submariner-io/submariner/files/14820503/Site2-2.txt)

Output errors seen while executing subctl gather commands
On Site 2 
```
sh-4.4$ /root/.local/bin/subctl gather --kubeconfig /tmp/local-kubeconfig 
Cluster "local-config"
Gathering information from cluster "local-config"
 ✓ Gathering connectivity logs 
 ✓ Found 3 pods matching label selector "app=submariner-gateway"
 ✓ Found 6 pods matching label selector "app=submariner-routeagent"
 ✓ Found 3 pods matching label selector "app=submariner-metrics-proxy"
 ✓ Found 0 pods matching label selector "app=submariner-globalnet"
 ✓ Found 0 pods matching label selector "app=submariner-addon"
 ✓ Gathering connectivity resources 
 ✓ Gathering CNI data from 6 pods matching label selector "app=submariner-routeagent"
 ✓ Gathering CNI data from 3 pods matching label selector "app=submariner-gateway"
 ✓ Gathering cable driver data from 3 pods matching label selector "app=submariner-gateway"
 ✓ Gathering OVN data from OVN kube pod "ovnkube-node-9mlh7"
 ✓ Gathering OVN data from OVN kube pod "ovnkube-node-9ttg6"
 ✓ Gathering OVN data from OVN kube pod "ovnkube-node-d4b22"
 ✓ Gathering OVN data from OVN kube pod "ovnkube-node-nxggc"
 ✓ Gathering OVN data from OVN kube pod "ovnkube-node-slbgr"
 ✓ Gathering OVN data from OVN kube pod "ovnkube-node-xwz9v"
 ✓ Found 1 gatewayroutes in namespace ""
 ✓ Found 1 nongatewayroutes in namespace ""
 ✓ Found 2 endpoints in namespace "submariner-operator"
 ✓ Found 2 clusters in namespace "submariner-operator"
 ✓ Found 3 gateways in namespace "submariner-operator"
 ✓ Found 0 clusterglobalegressips in namespace ""
 ✓ Found 0 globalegressips in namespace ""
 ✓ Found 0 globalingressips in namespace ""
 ✓ Gathering service-discovery logs 
 ✓ Found 3 pods matching label selector "component=submariner-lighthouse"
 ✓ Found 6 pods matching label selector "dns.operator.openshift.io/daemonset-dns=default"
 ✓ Gathering service-discovery resources 
 ✓ Found 0 serviceexports in namespace ""
 ✓ Found 0 serviceimports in namespace ""
 ✓ Found 0 endpointslices by label selector "endpointslice.kubernetes.io/managed-by=lighthouse-agent.submariner.io" in namespace ""
 ✓ Found 1 configmaps by label selector "component=submariner-lighthouse" in namespace "submariner-operator"
 ✓ Found 1 configmaps by field selector "metadata.name=dns-default" in namespace "openshift-dns"
 ✓ Found 0 services by label selector "submariner.io/exportedServiceRef" in namespace ""
 ✓ Gathering broker logs
 ✗ Gathering broker resources 
 ✗ Error getting the broker's rest config: error getting auth rest config: Unauthorized
 ✓ Gathering operator logs 
 ✓ Found 1 pods matching label selector "name=submariner-operator"
 ✓ Gathering operator resources 
 ✓ Found 1 submariners in namespace "submariner-operator"
 ✓ Found 1 servicediscoveries in namespace "submariner-operator"
 ✓ Found 1 deployments by field selector "metadata.name=submariner-operator" in namespace "submariner-operator"
 ✓ Found 1 daemonsets by label selector "app=submariner-gateway" in namespace "submariner-operator"
 ✓ Found 1 daemonsets by label selector "app=submariner-metrics-proxy" in namespace "submariner-operator"
 ✓ Found 1 daemonsets by label selector "app=submariner-routeagent" in namespace "submariner-operator"
 ✓ Found 0 daemonsets by label selector "app=submariner-globalnet" in namespace "submariner-operator"
 ✓ Found 1 deployments by label selector "app=submariner-lighthouse-agent" in namespace "submariner-operator"
 ✓ Found 1 deployments by label selector "app=submariner-lighthouse-coredns" in namespace "submariner-operator"
 Files are stored under directory "submariner-20240401061735/local-config"

Encountered following Kubernetes warnings while running:
Warning: Use tokens from the TokenRequest API or manually created secret-based tokens instead of auto-generated secret-based tokens.
```
```

sh-4.4$ /root/.local/bin/subctl gather --kubeconfig /connection/kube-config/71a5f5abfc/kubeconfig 
Cluster "default-cluster"
Gathering information from cluster "default-cluster"
 ⚠ Gathering connectivity logs 
 ✓ Found 3 pods matching label selector "app=submariner-gateway"
 ⚠ Found logs for previous instances of pod submariner-gateway-cfsrk
 ⚠ Found logs for previous instances of pod submariner-gateway-gf4x9
 ⚠ Found logs for previous instances of pod submariner-gateway-zvwhm
 ✓ Found 6 pods matching label selector "app=submariner-routeagent"
 ✓ Found 3 pods matching label selector "app=submariner-metrics-proxy"
 ✓ Found 0 pods matching label selector "app=submariner-globalnet"
 ✓ Found 0 pods matching label selector "app=submariner-addon"
 ✓ Gathering connectivity resources 
 ✓ Gathering CNI data from 6 pods matching label selector "app=submariner-routeagent"
 ✓ Gathering CNI data from 3 pods matching label selector "app=submariner-gateway"
 ✓ Gathering cable driver data from 3 pods matching label selector "app=submariner-gateway"
 ✓ Gathering OVN data from OVN kube pod "ovnkube-node-b5z4w"
 ✓ Gathering OVN data from OVN kube pod "ovnkube-node-k6sfw"
 ✓ Gathering OVN data from OVN kube pod "ovnkube-node-l5qkc"
 ✓ Gathering OVN data from OVN kube pod "ovnkube-node-s6fx4"
 ✓ Gathering OVN data from OVN kube pod "ovnkube-node-twhhw"
 ✓ Gathering OVN data from OVN kube pod "ovnkube-node-vn7jz"
 ✓ Found 1 gatewayroutes in namespace ""
 ✓ Found 1 nongatewayroutes in namespace ""
 ✓ Found 2 endpoints in namespace "submariner-operator"
 ✓ Found 2 clusters in namespace "submariner-operator"
 ✓ Found 1 gateways in namespace "submariner-operator"
 ✓ Found 0 clusterglobalegressips in namespace ""
 ✓ Found 0 globalegressips in namespace ""
 ✓ Found 0 globalingressips in namespace ""
 ✓ Gathering service-discovery logs 
 ✓ Found 3 pods matching label selector "component=submariner-lighthouse"
 ✓ Found 6 pods matching label selector "dns.operator.openshift.io/daemonset-dns=default"
 ✓ Gathering service-discovery resources 
 ✓ Found 0 serviceexports in namespace ""
 ✓ Found 0 serviceimports in namespace ""
 ✓ Found 0 endpointslices by label selector "endpointslice.kubernetes.io/managed-by=lighthouse-agent.submariner.io" in namespace ""
 ✓ Found 1 configmaps by label selector "component=submariner-lighthouse" in namespace "submariner-operator"
 ✓ Found 1 configmaps by field selector "metadata.name=dns-default" in namespace "openshift-dns"
 ✓ Found 0 services by label selector "submariner.io/exportedServiceRef" in namespace ""
 ✓ Gathering broker logs
 ✗ Gathering broker resources 
 ✗ Error getting the broker's rest config: error getting auth rest config: Unauthorized
 ✓ Gathering operator logs 
 ✓ Found 1 pods matching label selector "name=submariner-operator"
 ✓ Gathering operator resources 
 ✓ Found 1 submariners in namespace "submariner-operator"
 ✓ Found 1 servicediscoveries in namespace "submariner-operator"
 ✓ Found 1 deployments by field selector "metadata.name=submariner-operator" in namespace "submariner-operator"
 ✓ Found 1 daemonsets by label selector "app=submariner-gateway" in namespace "submariner-operator"
 ✓ Found 1 daemonsets by label selector "app=submariner-metrics-proxy" in namespace "submariner-operator"
 ✓ Found 1 daemonsets by label selector "app=submariner-routeagent" in namespace "submariner-operator"
 ✓ Found 0 daemonsets by label selector "app=submariner-globalnet" in namespace "submariner-operator"
 ✓ Found 1 deployments by label selector "app=submariner-lighthouse-agent" in namespace "submariner-operator"
 ✓ Found 1 deployments by label selector "app=submariner-lighthouse-coredns" in namespace "submariner-operator"
Files are stored under directory "submariner-20240401061805/default-cluster" 
```

**Comment by BhavaniYalamanchili** [comment] 2024-04-01 09:59
Also found an OCP ticket https://access.redhat.com/solutions/7032599 with similar error terms
Can you please go through and detail the root cause and solution for it?

**Comment by dfarrell07** [comment] 2024-04-02 13:20
@BhavaniYalamanchili which infra provider are you using? This looks a bit like an issue we've seen related to security groups not being created (your ticket also seems to confirm), but AFAIK we've only seen it in VMWare/IBM.

https://github.com/stolostron/submariner-addon/issues/1372

It also look like an issue we've seen related to pod security changes in OCP with SCC labels not being added. What Submariner version originally deployed the broker?

https://github.com/submariner-io/shipyard/pull/1024

Are you using ACM? I think part of the issue is that with ACM the upgrade process would keep you with matching/supported versions.

**Comment by BhavaniYalamanchili** [comment] 2024-04-03 06:03
@dfarrell07 
This is IBM infra
The broker is originally deployed with the submariner version 0.16.3
and we are not using the ACM 

As a workaround, if we reinstall it works fine, but we don't want to the reinstall every time when we hit this issue

**Comment by BhavaniYalamanchili** [comment] 2024-04-04 08:56
@dfarrell07 
Can you please provide us with a resolution?

**Comment by BhavaniYalamanchili** [comment] 2024-04-05 11:29
We have another setup that has both the sites on OCP 4.12 with submariner running in good state and when we compared it with the setup where the OCP upgrade is stuck
We found the differences that not all the secrets are present in both the namespaces**(submariner-operator and submariner-k8s-broker)** on Site 1

Site - 1 submariner-k8s-broker namespace secrets list on the setup with issue
<img width="1728" alt="Site-1 submariner-k8s-broker ns secrets Setup1" src="https://github.com/submariner-io/submariner/assets/60847572/9b087b40-7c09-49f3-9f7f-7eaf48fe1f3d">

Site - 1 submariner-k8s-broker namespace secrets list on the setup with no issue
<img width="1728" alt="Site-1 submariner-k8s-broker ns secrets Setup2" src="https://github.com/submariner-io/submariner/assets/60847572/79fa1c33-47fc-4b45-a8e9-b56404dd671a">

Site - 1 submariner-operator namespace secrets list on the setup with issue
<img width="1728" alt="Site-1 submariner-operator ns secrets Setup1" src="https://github.com/submariner-io/submariner/assets/60847572/9fc29031-fcb5-4ee4-8b31-e8724e741605">

Site - 1 submariner-operator namespace secrets list on the setup with no issue
<img width="1728" alt="Site-1 submariner-operator ns secrets Setup2" src="https://github.com/submariner-io/submariner/assets/60847572/fff31796-15b4-450d-9343-5e4faf589aa0">


@dfarrell07 @yboaron @tpantelis 
Kindly help us with a resolution for this, we need this issue to be solved on a priority

**Comment by tpantelis** [comment] 2024-04-05 12:08
Somewhere along the line K8s no longer auto-creates the service account secrets so we modified `subctl join` to do 
 so manually. Re-running `subctl join` should re-create them.

**Comment by BhavaniYalamanchili** [comment] 2024-04-05 13:54
@tpantelis 
Should the `subctl join` command be run for both sites? or only the Site1?

And another question
As you said you have modified the `subctl join` command, will we hit this issue again in any scenario?

**Comment by tpantelis** [comment] 2024-04-05 14:06
> @tpantelis Should the `subctl join` command be run for both sites? or only the Site1?
> 

Run it on whichever clusters are missing the secrets.

> And another question As you said you have modified the `subctl join` command, will we hit this issue again in any scenario?

You shouldn't. Once created, the secrets should remain static unless there's something strange in K8s or OCP whereby they get deleted. We don't touch them after creation.

**Comment by BhavaniYalamanchili** [comment] 2024-04-05 14:08
Thanks @tpantelis will try it and update you here, once complete

**Comment by BhavaniYalamanchili** [comment] 2024-04-05 15:45
I have run the `subctl join` command for both the sites because it did not work after the just running for Site1 

```
sh-4.4$ /root/.local/bin/subctl join --kubeconfig=/connection/kube-config/71a5f5abfc/kubeconfig --operator-debug --pod-debug --clusterid=site1 broker-info.subm
 ✓ broker-info.subm indicates broker is at https://api.rackae1.mydomain.com:6443
 ✓ Discovering network details
        Network plugin:  OVNKubernetes
        Service CIDRs:   [172.30.0.0/16]
        Cluster CIDRs:   [10.128.0.0/14]
   There are 3 node(s) labeled as gateways:
    - control-1-ru2.rackae1.mydomain.com
    - control-1-ru3.rackae1.mydomain.com
    - control-1-ru4.rackae1.mydomain.com
 ✓ Retrieving the gateway nodes
 ✓ Gathering relevant information from Broker 
 ✓ Retrieving Globalnet information from the Broker
 ✓ Validating Globalnet configuration
 ✓ Deploying the Submariner operator 
 ✓ Created operator namespace: submariner-operator
 ✓ Creating SA for cluster 
 ✓ Connecting to Broker
 ✓ Deploying submariner 
 ✓ Submariner is up and running
sh-4.4$ /root/.local/bin/subctl diagnose all --kubeconfig /tmp/local-kubeconfig Cluster "local-config"
 ✓ Checking Submariner support for the Kubernetes version
 ✓ Kubernetes version "v1.27.11+d8e449a" is supported

 ✗ Non-Globalnet deployment detected - checking that cluster CIDRs do not overlap 
 ✗ Error getting the Broker's REST config: error getting auth rest config: Unauthorized

 ✓ Checking Submariner support for the CNI network plugin
 ✓ The detected CNI network plugin ("OVNKubernetes") is supported
 ✓ Checking OVN version 
 ✓ The ovn-nb database version 7.1.0 is supported
 ✗ Checking gateway connections
 ✗ Connection to cluster "site1" is in progress
 ✓ Checking Submariner support for the kube-proxy mode
 ✓ Cluster is running with "OVNKubernetes" CNI which internally implements kube-proxy functionality
 ✓ Checking that firewall configuration allows intra-cluster VXLAN traffic

 ✓ Checking that services have been exported properly

Skipping inter-cluster firewall check as it requires two kubeconfigs. Please run "subctl diagnose firewall inter-cluster" command manually.

subctl version: v0.16.3

sh-4.4$ /root/.local/bin/subctl diagnose all --kubeconfig /connection/kube-config/71a5f5abfc/kubeconfig 
Cluster "default-cluster"
 ✓ Checking Submariner support for the Kubernetes version
 ✓ Kubernetes version "v1.28.7+f1b5f6c" is supported

 ✓ Non-Globalnet deployment detected - checking that cluster CIDRs do not overlap 
 ✓ Checking DaemonSet "submariner-gateway"
 ✓ Checking DaemonSet "submariner-routeagent"
 ✓ Checking DaemonSet "submariner-metrics-proxy"
 ✓ Checking Deployment "submariner-lighthouse-agent"
 ✓ Checking Deployment "submariner-lighthouse-coredns"
 ✓ Checking the status of all Submariner pods
 ✓ Checking that gateway metrics are accessible from non-gateway nodes 

 ✓ Checking Submariner support for the CNI network plugin
 ✓ The detected CNI network plugin ("OVNKubernetes") is supported
 ✓ Checking OVN version 
 ✓ The ovn-nb database version 7.1.0 is supported
 ✗ Checking gateway connections
 ✗ Connection to cluster "site2" is in progress
 ✓ Checking Submariner support for the kube-proxy mode
 ✓ Cluster is running with "OVNKubernetes" CNI which internally implements kube-proxy functionality
 ✓ Checking that firewall configuration allows intra-cluster VXLAN traffic

 ✓ Checking that services have been exported properly

Skipping inter-cluster firewall check as it requires two kubeconfigs. Please run "subctl diagnose firewall inter-cluster" command manually.

subctl version: v0.16.3

sh-4.4$ /root/.local/bin/subctl join --kubeconfig=/tmp/local-kubeconfig --operator-debug --pod-debug --clusterid=site2 broker-info.subm ✓ broker-info.subm indicates broker is at https://api.rackae1.mydomain.com:6443
 ✓ Discovering network details
        Network plugin:  OVNKubernetes
        Service CIDRs:   [172.31.0.0/16]
        Cluster CIDRs:   [10.132.0.0/14]
   There are 3 node(s) labeled as gateways:
    - control-1-ru2.rackae2.mydomain.com
    - control-1-ru3.rackae2.mydomain.com
    - control-1-ru4.rackae2.mydomain.com
 ✓ Retrieving the gateway nodes
 ✓ Gathering relevant information from Broker 
 ✓ Retrieving Globalnet information from the Broker
 ✓ Validating Globalnet configuration
 ✓ Deploying the Submariner operator 
 ✓ Created operator namespace: submariner-operator
 ✓ Creating SA for cluster 
 ✓ Connecting to Broker
 ✓ Deploying submariner 
 ✓ Submariner is up and running
sh-4.4$ /root/.local/bin/subctl diagnose all --kubeconfig /tmp/local-kubeconfig 
Cluster "local-config"
 ✓ Checking Submariner support for the Kubernetes version
 ✓ Kubernetes version "v1.27.11+d8e449a" is supported

 ✓ Non-Globalnet deployment detected - checking that cluster CIDRs do not overlap 
 ✓ Checking DaemonSet "submariner-gateway"
 ✓ Checking DaemonSet "submariner-routeagent"
 ✓ Checking DaemonSet "submariner-metrics-proxy"
 ✓ Checking Deployment "submariner-lighthouse-agent"
 ✓ Checking Deployment "submariner-lighthouse-coredns"
 ✓ Checking the status of all Submariner pods
 ✓ Checking that gateway metrics are accessible from non-gateway nodes 

 ✓ Checking Submariner support for the CNI network plugin
 ✓ The detected CNI network plugin ("OVNKubernetes") is supported
 ✓ Checking OVN version 
 ✓ The ovn-nb database version 7.1.0 is supported
 ✓ Checking gateway connections
 ✓ Checking Submariner support for the kube-proxy mode
 ✓ Cluster is running with "OVNKubernetes" CNI which internally implements kube-proxy functionality
 ✓ Checking that firewall configuration allows intra-cluster VXLAN traffic

 ✓ Checking that services have been exported properly


Skipping inter-cluster firewall check as it requires two kubeconfigs. Please run "subctl diagnose firewall inter-cluster" command manually.
sh-4.4$ /root/.local/bin/subctl diagnose all --kubeconfig /connection/kube-config/71a5f5abfc/kubeconfig 
Cluster "default-cluster"
 ✓ Checking Submariner support for the Kubernetes version
 ✓ Kubernetes version "v1.28.7+f1b5f6c" is supported

 ✓ Non-Globalnet deployment detected - checking that cluster CIDRs do not overlap 
 ✓ Checking DaemonSet "submariner-gateway"
 ✓ Checking DaemonSet "submariner-routeagent"
 ✓ Checking DaemonSet "submariner-metrics-proxy"
 ✓ Checking Deployment "submariner-lighthouse-agent"
 ✓ Checking Deployment "submariner-lighthouse-coredns"
 ✓ Checking the status of all Submariner pods
 ✓ Checking that gateway metrics are accessible from non-gateway nodes 

 ✓ Checking Submariner support for the CNI network plugin
 ✓ The detected CNI network plugin ("OVNKubernetes") is supported
 ✓ Checking OVN version 
 ✓ The ovn-nb database version 7.1.0 is supported
 ✓ Checking gateway connections
 ✓ Checking Submariner support for the kube-proxy mode
 ✓ Cluster is running with "OVNKubernetes" CNI which internally implements kube-proxy functionality
 ✓ Checking that firewall configuration allows intra-cluster VXLAN traffic

 ✓ Checking that services have been exported properly

```

@tpantelis we have some more questions 

1. Could you confirm when the join command modification went in and in which version? and will the join command depend on the version?
2. a. Also considering a case where we had submariner running in our setup already for a few days ago(like say a month or two), as you said the subctl join command has been modified to create service account secrets manually, then we should reinstall the submariner again, right, or not needed?
b. If not needed we need to see that the OCP doesn't remove the secrets right? If so for the record could you confirm the secrets being used by the submariner and how to make them stop from being deleted?

**Comment by tpantelis** [comment] 2024-04-05 17:39
> 1. Could you confirm when the join command modification went in and in which version? and will the join command depend on the version?

Here's the PR https://github.com/submariner-io/subctl/pull/125 - merged almost 2 years ago - looks like V0.13.

> 2. a. Also considering a case where we had submariner running in our setup already for a few days ago(like say a month or two), as you said the subctl join command has been modified to create service account secrets manually, then we should reinstall the submariner again, right, or not needed?

I'm not sure I follow... all I can say is if the secrets are missing for some reason then re-joining will re-create them.

>    b. If not needed we need to see that the OCP doesn't remove the secrets right? If so for the record could you confirm the secrets being used by the submariner and how to make them stop from being deleted?

If there were/are deleted, I'm not sure why that would occur.

**Comment by BhavaniYalamanchili** [comment] 2024-04-08 06:32
@tpantelis 
Can you provide troubleshooting steps for identifying this specific issue through these specific error messages or logs indicating that secrets are missing so we have to perform `subctl join` commands

**Comment by tpantelis** [comment] 2024-04-08 13:03
> @tpantelis Can you provide troubleshooting steps for identifying this specific issue through these specific error messages or logs indicating that secrets are missing so we have to perform `subctl join` commands

When running subclt diagnose you'll see "Error getting the Broker's REST config: error getting auth rest config: Unauthorized" or you'll see a similar error in a pod log.

**Comment by BhavaniYalamanchili** [comment] 2024-04-10 06:34
@tpantelis 
Will this error message in the subctl diagnose command only be seen when secrets are removed while the OCP upgrade or any other issue regarding the submariner also show up with this error message?

Asking this because we want to handle this specific issue only, and don't want to run the join commands unnecessarily multiple times for another issue(if the error message shows up for another issue), which may affect something else.

**Comment by tpantelis** [comment] 2024-04-10 11:47
> @tpantelis Will this error message in the subctl diagnose command only be seen when secrets are removed while the OCP upgrade or any other issue regarding the submariner also show up with this error message?

The "Unauthorized" part of the message is the underlying error which comes from K8s which I think could occur for any reason indicating a permissions issue.

**Comment by BhavaniYalamanchili** [comment] 2024-04-23 14:14
Hi @tpantelis 
Another doubt,

What if other secrets(other than broker secret) are deleted by a user, will they cause any issue and if so how to identify them and what is the resolution?

**Comment by tpantelis** [comment] 2024-04-23 14:40
> Hi @tpantelis Another doubt,
> 
> What if other secrets(other than broker secret) are deleted by a user, will they cause any issue and if so how to identify them and what is the resolution?

Why would a user delete a secret - they shouldn't do that. If Submariner, like any other product/tool, installs or creates something, it's not intended for someone to just delete it. If they do, accidentally or purposely, then expect something not to work right and you may have to reinstall.

**Comment by BhavaniYalamanchili** [comment] 2024-06-13 15:57
Sorry for the late reply @tpantelis

> Why would a user delete a secret - they shouldn't do that. If Submariner, like any other product/tool, installs or creates something, it's not intended for someone to just delete it. If they do, accidentally or purposely, then expect something not to work right and you may have to reinstall.

You are right no user would delete the secret, I was asking in the context of a user accidentally deleting the secret. Thank you @tpantelis for the Answer.

**Closed as completed** 2024-06-24 14:07 UTC
Labels: support
