### ISSUE TITLE
Globalnet connections are in error when using `0.13.0-rc0`

### ISSUE THREAD

**Issue by mkolesnik** [submariner-io/submariner#1881] opened 2022-06-22 10:22 UTC
**What happened**:
Deployed with 0.13.0-rc0 (default cable driver) following the quickstart kind guide, the connections are in error.

**What you expected to happen**:
Globalnet should be working.

**How to reproduce it (as minimally and precisely as possible)**:
```sh
make clusters using=globalnet
curl -Ls https://get.submariner.io | VERSION=0.13.0-rc0
subctl deploy-broker --kubeconfig output/kubeconfigs/kind-config-cluster1 --globalnet
subctl join --kubeconfig output/kubeconfigs/kind-config-cluster1 broker-info.subm --clusterid cluster1 --natt=false
subctl join --kubeconfig output/kubeconfigs/kind-config-cluster2 broker-info.subm --clusterid cluster2 --natt=false
```

**Anything else we need to know?**:

**Environment**:
- Diagnose information (use `subctl diagnose all`):
```sh
[root@ddd7db0e0dfe submariner-operator]# subctl diagnose all
Cluster "cluster2"
 ✓ Checking Submariner support for the Kubernetes version
 ✓ Kubernetes version "v1.23.4" is supported

 ✓ Checking Submariner support for the CNI network plugin
 ✓ The detected CNI network plugin ("weave-net") is supported
 ✓ Trying to detect the Calico ConfigMap

 ✗ Checking gateway connections
 ✗ Connection to cluster ["cluster1"] is not established

 ✓ Globalnet deployment detected - checking if globalnet CIDRs overlap
 ✓ Clusters do not have overlapping globalnet CIDRs
 ✓ Checking Submariner pods
 ✓ All Submariner pods are up and running

 ✓ Checking Submariner support for the kube-proxy mode 
 ✓ The kube-proxy mode is supported

 ✓ Checking the firewall configuration to determine if the metrics port (8080) is allowed 
 ✓ The firewall configuration allows metrics to be retrieved from Gateway nodes

 ✓ Checking the firewall configuration to determine if intra-cluster VXLAN traffic is allowed 
 ✓ The firewall configuration allows intra-cluster VXLAN traffic

 ✓ Checking Globalnet configuration
 ✓ Globalnet is properly configured and functioning

Skipping inter-cluster firewall check as it requires two kubeconfigs. Please run "subctl diagnose firewall inter-cluster" command manually.

Cluster "cluster1"
 ✓ Checking Submariner support for the Kubernetes version
 ✓ Kubernetes version "v1.23.4" is supported

 ✓ Checking Submariner support for the CNI network plugin
 ✓ The detected CNI network plugin ("weave-net") is supported
 ✓ Trying to detect the Calico ConfigMap

 ✗ Checking gateway connections
 ✗ Connection to cluster ["cluster2"] is not established

 ✓ Globalnet deployment detected - checking if globalnet CIDRs overlap
 ✓ Clusters do not have overlapping globalnet CIDRs
 ✓ Checking Submariner pods
 ✓ All Submariner pods are up and running

 ✓ Checking Submariner support for the kube-proxy mode 
 ✓ The kube-proxy mode is supported

 ✓ Checking the firewall configuration to determine if the metrics port (8080) is allowed 
 ✓ The firewall configuration allows metrics to be retrieved from Gateway nodes

 ✓ Checking the firewall configuration to determine if intra-cluster VXLAN traffic is allowed 
 ✓ The firewall configuration allows intra-cluster VXLAN traffic

 ✓ Checking Globalnet configuration
 ✓ Globalnet is properly configured and functioning

Skipping inter-cluster firewall check as it requires two kubeconfigs. Please run "subctl diagnose firewall inter-cluster" command manually.
```
- Gather information (use `subctl gather`):
[gather.tar.gz](https://github.com/submariner-io/submariner/files/8956689/gather.tar.gz)

- Cloud provider or hardware configuration: KIND (K8s 1.23.4)
- Install tools: subctl 0.13.0-rc0
- Others:

**Comment by sridhargaddam** [comment] 2022-06-22 13:32
It looks like the pinger is unable to perform the healthcheck, hence its marking the connection as error.

```
    latencyRTT:
      average: 0s
      last: 0s
      max: 0s
      min: 0s
      stdDev: 0s
    status: error
    statusMessage: Failed to successfully ping the remote endpoint IP "242.1.255.254"
    usingIP: 172.20.0.6
  haStatus: active
```

**Comment by nyechiel** [comment] 2022-06-22 20:40
FWIW, I just tried it locally out of the `submariner-operator` repo and everything seems to be working as expected:

```
$ kubectl describe pods -n submariner-operator submariner-routeagent-tp4h9 | grep Image
    Image:         quay.io/submariner/submariner-route-agent:0.13.0-rc0
    Image ID:      quay.io/submariner/submariner-route-agent@sha256:e99eda1dcdd9dc19c617a4f7821d3cf1076564567374bdf6df53f54a7d991391
```

```
$ subctl show connections
Cluster "cluster2"
 ✓ Showing Connections
GATEWAY          CLUSTER   REMOTE IP   NAT  CABLE DRIVER  SUBNETS       STATUS     RTT avg.    
cluster1-worker  cluster1  172.19.0.7  no   libreswan     242.0.0.0/16  connected  445.261µs   

Cluster "cluster1"
 ✓ Showing Connections
GATEWAY          CLUSTER   REMOTE IP   NAT  CABLE DRIVER  SUBNETS       STATUS     RTT avg.    
cluster2-worker  cluster2  172.19.0.5  no   libreswan     242.1.0.0/16  connected  427.572µs   
```
```

$ kubectl describe Gateway -n submariner-operator
Name:         cluster2-worker
Namespace:    submariner-operator
Labels:       <none>
Annotations:  update-timestamp: 1655930127
API Version:  submariner.io/v1
Kind:         Gateway
Metadata:
  Creation Timestamp:  2022-06-22T20:32:10Z
  Generation:          39
  Managed Fields:
    API Version:  submariner.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:update-timestamp:
      f:status:
        .:
        f:connections:
        f:haStatus:
        f:localEndpoint:
          .:
          f:backend:
          f:backend_config:
            .:
            f:natt-discovery-port:
            f:preferred-server:
            f:udp-port:
          f:cable_name:
          f:cluster_id:
          f:hostname:
          f:nat_enabled:
          f:private_ip:
          f:public_ip:
          f:subnets:
        f:statusFailure:
        f:version:
    Manager:         submariner-gateway
    Operation:       Update
    Time:            2022-06-22T20:32:10Z
  Resource Version:  2194
  UID:               1adb09c8-4f1e-4fa6-b2de-b3d778cfdeac
Status:
  Connections:
    Endpoint:
      Backend:  libreswan
      backend_config:
        Natt - Discovery - Port:  4490
        Preferred - Server:       false
        Udp - Port:               4500
      cable_name:                 submariner-cable-cluster1-172-19-0-7
      cluster_id:                 cluster1
      Health Check IP:            242.0.255.254
      Hostname:                   cluster1-worker
      nat_enabled:                false
      private_ip:                 172.19.0.7
      public_ip:                  84.229.249.187
      Subnets:
        242.0.0.0/16
    Latency RTT:
      Average:       448.471µs
      Last:          607.857µs
      Max:           1.215716ms
      Min:           127.406µs
      Std Dev:       158.416µs
    Status:          connected
    Status Message:  
    Using IP:        172.19.0.7
  Ha Status:         active
  Local Endpoint:
    Backend:  libreswan
    backend_config:
      Natt - Discovery - Port:  4490
      Preferred - Server:       false
      Udp - Port:               4500
    cable_name:                 submariner-cable-cluster2-172-19-0-5
    cluster_id:                 cluster2
    Hostname:                   cluster2-worker
    nat_enabled:                false
    private_ip:                 172.19.0.5
    public_ip:                  84.229.249.187
    Subnets:
      242.1.0.0/16
  Status Failure:  
  Version:         release-0.13-ffef6b8
Events:            <none>

```

**Comment by nyechiel** [comment] 2022-06-24 13:00
Might be related to https://github.com/submariner-io/submariner/issues/1857

**Comment by yboaron** [comment] 2022-06-27 11:25
I managed to reproduce it on my setup, seems that the iptable rule redirects traffic to SUBMARINER-POSTROUTING chain doesn't exist on GW node (on one of the clusters)

`# iptables -t nat -L -n -v 
Chain PREROUTING (policy ACCEPT 90 packets, 16738 bytes)
 pkts bytes target     prot opt in     out     source               destination         
 2897  543K SUBMARINER-GN-INGRESS  all  --  *      *       0.0.0.0/0            0.0.0.0/0           

Chain INPUT (policy ACCEPT 10 packets, 738 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain OUTPUT (policy ACCEPT 670 packets, 34269 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain POSTROUTING (policy ACCEPT 670 packets, 34269 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain SM-GN-EGRESS-CLUSTER (1 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 SNAT       all  --  *      *       10.1.0.0/16          0.0.0.0/0            mark match 0xc0000/0xc0000 to:242.0.0.1-242.0.0.8
    0     0 SNAT       all  --  *      *       100.1.0.0/16         0.0.0.0/0            mark match 0xc0000/0xc0000 to:242.0.0.1-242.0.0.8

Chain SM-GN-EGRESS-HDLS-EPS (1 references)
 pkts bytes target     prot opt in     out     source               destination         

Chain SM-GN-EGRESS-HDLS-PODS (1 references)
 pkts bytes target     prot opt in     out     source               destination         

Chain SM-GN-EGRESS-NS (1 references)
 pkts bytes target     prot opt in     out     source               destination         

Chain SM-GN-EGRESS-PODS (1 references)
 pkts bytes target     prot opt in     out     source               destination         

Chain SUBMARINER-GN-EGRESS (1 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 SUBMARINER-GN-MARK  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
    0     0 SM-GN-EGRESS-PODS  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
    0     0 SM-GN-EGRESS-HDLS-PODS  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
    0     0 SM-GN-EGRESS-HDLS-EPS  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
    0     0 SM-GN-EGRESS-NS  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
    0     0 SM-GN-EGRESS-CLUSTER  all  --  *      *       0.0.0.0/0            0.0.0.0/0           

Chain SUBMARINER-GN-INGRESS (1 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 DNAT       icmp --  *      *       0.0.0.0/0            242.0.255.254        to:10.1.128.0

Chain SUBMARINER-GN-MARK (1 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 MARK       all  --  *      *       0.0.0.0/0            242.1.0.0/16         MARK or 0xc0000

Chain SUBMARINER-POSTROUTING (0 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 SUBMARINER-GN-EGRESS  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
sh-5.1#`

**Comment by yboaron** [comment] 2022-06-28 09:27
Seems that the root cause is missing grep in GN image, so iptables legacy version is used by GN while iptables nft version is used by RA pod.

When I exec 'iptables -t nat -L -n -v'  from GN pod I can only see the rules added by GN  pod, and can't see all the rules created by others (KUBE and RA , etc ) while exec 'iptables -t nat -L -n -v'  from RA pod (on GW node) I can see all the rules created by RA KUBE but the rules created by GN are missing.

After reinstalling the Submariner with GN image that includes grep all connections seems OK.

**Comment by skitt** [comment] 2022-06-28 09:41
So this is fixed by https://github.com/submariner-io/submariner/pull/1888

**Closed as completed by skitt** 2022-06-28 09:41 UTC
Labels: bug, priority:high, 0.13.0-testday

**Comment by nyechiel** [comment] 2022-06-28 10:59
Awesome, thanks @yboaron

**Comment by mkolesnik** [comment] 2022-06-29 08:34
I can confirm this works for me with the `devel` images
