### ISSUE TITLE
kubectl get serviceexport with "-o wide" does not show more info 

### ISSUE THREAD

**Issue by manosnoam** [submariner-io/submariner#739] opened 2020-07-23 18:39 UTC
```

$ oc get serviceexport "nginx-cl-b"
NAME         AGE
nginx-cl-b   9m7s

$ oc get serviceexport "nginx-cl-b" -o wide
NAME         AGE
nginx-cl-b   9m13s
```

**What would you like to be added**:

Please show more info with the "-o wide" option enabled.

**Comment by tpantelis** [comment] 2020-07-23 20:58
What more information would you like to see? Other than the standard k8s metadata, `ServiceExport` has a `Status` field that is an array so wouldn't seem suitable as columnar data. For that use '-o=yaml' or `kubectl describe`.

**Comment by manosnoam** [comment] 2020-07-26 09:07
Looking at:
```
$ oc get serviceexport "nginx-cl-b"  -o yaml

apiVersion: lighthouse.submariner.io/v2alpha1
kind: ServiceExport
metadata:
  creationTimestamp: "2020-07-26T05:32:51Z"
  generation: 2
  name: nginx-cl-b
  namespace: test-submariner
  resourceVersion: "6803005"
  selfLink: /apis/lighthouse.submariner.io/v2alpha1/namespaces/test-submariner/serviceexports/nginx-cl-b
  uid: 70db9f33-4aa5-4aca-ae13-23439eac7655
status:
  conditions:
  - message: Service was successfully synced to the broker
    status: "True"
    type: Exported
```

I would say we can add columns for:

- FQDN (or at least namespace and supercluster suffix), 
- Creation time
- And maybe rename "status" to "Exported" (btw, when could the status be false ?)

@nyechiel, @mangelajo what do you think ?

**Comment by aswinsuryan** [comment] 2020-07-28 12:33
> Looking at:
> 
> ```
> $ oc get serviceexport "nginx-cl-b"  -o yaml
> 
> apiVersion: lighthouse.submariner.io/v2alpha1
> kind: ServiceExport
> metadata:
>   creationTimestamp: "2020-07-26T05:32:51Z"
>   generation: 2
>   name: nginx-cl-b
>   namespace: test-submariner
>   resourceVersion: "6803005"
>   selfLink: /apis/lighthouse.submariner.io/v2alpha1/namespaces/test-submariner/serviceexports/nginx-cl-b
>   uid: 70db9f33-4aa5-4aca-ae13-23439eac7655
> status:
>   conditions:
>   - message: Service was successfully synced to the broker
>     status: "True"
>     type: Exported
> ```
> 
> I would say we can add columns for:
> 
> * FQDN (or at least namespace and supercluster suffix),
> * Creation time
> * And maybe rename "status" to "Exported" (btw, when could the status be false ?)
FQDN and supercluster is not a part of this CRD , it is configured in the configmap so it may not be relevant. 

When submariner-io/lighthouse/issues/226 fixed you could use "oc  wait" command, so you will have a way to retrieve status, do you think still think status is relevant here too?


> 
> @nyechiel, @mangelajo what do you think ?

**Comment by tpantelis** [comment] 2020-07-29 00:41
> When [submariner-io/lighthouse/issues/226](https://github.com/submariner-io/lighthouse/issues/226) fixed you could use "oc wait" command, so you will have a way to retrieve status, do you think still think status is relevant here too?
> 

I actually posed the question of whether or not the `Status` field adds any value last week on slack given the other fields (`Type`, `Reason`, and `Message`). But all these fields are defined in the u/s API so it seems we should stay consistent with it even though it hasn't been finalized. We actually did find a use case for `Status == false`, based on the u/s definition, in one case when `Type == Initialized` 😄

**Comment by aswinsuryan** [comment] 2020-07-29 05:21
In upstream spec the status have been changed from the time we started. It is now  of the format 

const {
      // ServiceExportValid means that the service referenced by this
      // service export has been recognized as valid by an mcs-controller.
      // This will be false if the service is found to be unexportable
      // (ExternalName, not found).
      ServiceExportValid ServiceExportConditionType = "Valid"
      // ServiceExportConflict means that there is a conflict between two
      // exports for the same Service. When "True", the condition message
      // should contain enough information to diagnose the conflict:
      // field(s) under contention, which cluster won, and why.
      // Users should not expect detailed per-cluster information in the
      // conflict message.
      ServiceExportConflict ServiceExportConditionType = "Conflict"
}


type ServiceExportCondition struct {
        Type ServiceExportConditionType `json:"type"`
        // Status is one of {"True", "False", "Unknown"}
        Status corev1.ConditionStatus `json:"status"`
        // +optional
        LastTransitionTime *metav1.Time `json:"lastTransitionTime,omitempty"`
        // +optional
        Reason *string `json:"reason,omitempty"`
        // +optional
        Message *string `json:"message,omitempty"`
}

an example would be 
status:
  conditions:
  - type: Ready
    status: "True"
    lastTransitionTime: "2020-03-30T01:33:51Z"
  - type: InvalidService
    status: "False"
    lastTransitionTime: "2020-03-30T01:33:55Z"
  - type: Conflict
    status: "True"
    lastTransitionTime: "2020-03-30T01:33:55Z"
    message: "Conflicting type. Using \"SuperclusterIP\" from oldest service export in \"cluster-1\". 2/5 clusters disagree."

So if this helps in kubectl commands, I think we can think of using the updated proposal.

**Comment by manosnoam** [comment] 2020-10-08 09:28
> In upstream spec the status fields have been changed from the time we started. 
> ...
> So if this helps in kubectl commands, I think we can think of using the updated proposal.

@aswinsuryan, did you resolve it ?

**Comment by aswinsuryan** [comment] 2020-10-14 07:22
This shall be done as a part of https://github.com/submariner-io/lighthouse/issues/336 or after the changes related to this issue is merged.

**Comment by nyechiel** [comment] 2020-11-30 07:36
@aswinsuryan now with the new CRDs, any change of behaviour that we just inherit?

**Comment by nyechiel** [comment] 2020-12-03 18:01
@manosnoam I am still not convinced that there is anything to fix here. If you want to get more info on a certain ServiceExport object, you can always use `kubectl describe`. 

@aswinsuryan now with the new MCS CRDs=, any change of behaviour that we just inherit?

**Comment by aswinsuryan** [comment] 2020-12-07 10:05
> @manosnoam I am still not convinced that there is anything to fix here. If you want to get more info on a certain ServiceExport object, you can always use `kubectl describe`.
> 
> @aswinsuryan now with the new MCS CRDs=, any change of behaviour that we just inherit?

I was expecting this to work , but seems to be not. Not sure if the syntax is correct. 

`kubectl -n default wait --for=condition=Valid --timeout=5s serviceexports.multicluster.x-k8s.io/nginx`

**Comment by manosnoam** [comment] 2020-12-21 07:43
Besides the current issue of no additional info for the `-o wide`, there's a weird behavior in the age (duration) when checking for serviceexport, with and w/o `-o wide` (notice the timestamps):

```
$ oc get serviceexport "nginx-cl-b"
08:40:23 NAME         AGE
08:40:23 nginx-cl-b   52s

$ oc get serviceexport "nginx-cl-b" -o jsonpath='{.status.conditions[?(@.status=="True")].type}' | grep "Valid"
08:40:24 Valid

$ oc get serviceexport "nginx-cl-b" ${namespace:+ -n $namespace} -o wide
08:40:25 NAME         AGE
08:40:25 nginx-cl-b   3s
```

full test report:
https://qe-jenkins-csb-skynet.cloud.paas.psi.redhat.com/job/Submariner-OSP-AWS-Globalnet/44/Test-Report/

**Comment by aswinsuryan** [comment] 2020-12-22 14:01
> Besides the current issue of no additional info for the `-o wide`, there's a weird behavior in the age (duration) when checking for serviceexport, with and w/o `-o wide` (notice the timestamps):
> 
> ```
> $ oc get serviceexport "nginx-cl-b"
> 08:40:23 NAME         AGE
> 08:40:23 nginx-cl-b   52s
> 
> $ oc get serviceexport "nginx-cl-b" -o jsonpath='{.status.conditions[?(@.status=="True")].type}' | grep "Valid"
> 08:40:24 Valid
> 
> $ oc get serviceexport "nginx-cl-b" ${namespace:+ -n $namespace} -o wide
> 08:40:25 NAME         AGE
> 08:40:25 nginx-cl-b   3s
> ```
> 
> full test report:
> https://qe-jenkins-csb-skynet.cloud.paas.psi.redhat.com/job/Submariner-OSP-AWS-Globalnet/44/Test-Report/

As discussed this seems to be not observed in the local setup and the Openshift setup. It could be since a subsequent test recreated the resource.

**Comment by aswinsuryan** [comment] 2020-12-22 14:04
@manosnoam If we could not reproduce the latest issue can we close this bug. I think now since it is a standard API  there is no much option to customize it unless it is really important.

**Comment by manosnoam** [comment] 2020-12-22 14:13
Today I saw a different response of the age: `<invalid>`

```
08:40:21 Name:         nginx-cl-b
08:40:21 Namespace:    test-submariner
08:40:21 Labels:       <none>
08:40:21 Annotations:  <none>
08:40:21 API Version:  multicluster.x-k8s.io/v1alpha1
08:40:21 Kind:         ServiceExport
08:40:21 Metadata:
08:40:21   Creation Timestamp:  2020-12-22T06:39:31Z
08:40:21   Generation:          1
08:40:21   Resource Version:    25028079
08:40:21   Self Link:           /apis/multicluster.x-k8s.io/v1alpha1/namespaces/test-submariner/serviceexports/nginx-cl-b
08:40:21   UID:                 a84ba48e-9ef1-4d69-9a65-c89548007d15
08:40:21 Status:
08:40:21   Conditions:
08:40:21     Last Transition Time:  2020-12-22T06:38:32Z
08:40:21     Message:               Awaiting sync of the ServiceImport to the broker
08:40:21     Reason:                AwaitingSync
08:40:21     Status:                False
08:40:21     Type:                  Valid
08:40:21     Last Transition Time:  2020-12-22T06:38:32Z
08:40:21     Message:               Service was successfully synced to the broker
08:40:21     Reason:                
08:40:21     Status:                True
08:40:21     Type:                  Valid
08:40:21 Events:                    <none>
08:40:21

$ oc get serviceexport "nginx-cl-b"
08:40:22 NAME         AGE
08:40:22 nginx-cl-b   <invalid>

# More info
08:40:24 apiVersion: multicluster.x-k8s.io/v1alpha1
08:40:24 kind: ServiceExport
08:40:24 metadata:
08:40:24   creationTimestamp: "2020-12-22T06:39:31Z"
08:40:24   generation: 1
08:40:24   name: nginx-cl-b
08:40:24   namespace: test-submariner
08:40:24   resourceVersion: "25028079"
08:40:24   selfLink: /apis/multicluster.x-k8s.io/v1alpha1/namespaces/test-submariner/serviceexports/nginx-cl-b
08:40:24   uid: a84ba48e-9ef1-4d69-9a65-c89548007d15
08:40:24 status:
08:40:24   conditions:
08:40:24   - lastTransitionTime: "2020-12-22T06:38:32Z"
08:40:24     message: Awaiting sync of the ServiceImport to the broker
08:40:24     reason: AwaitingSync
08:40:24     status: "False"
08:40:24     type: Valid
08:40:24   - lastTransitionTime: "2020-12-22T06:38:32Z"
08:40:24     message: Service was successfully synced to the broker
08:40:24     reason: ""
08:40:24     status: "True"
08:40:24     type: Valid
08:40:24 
08:40:24 # Describe Lighthouse Exported Services:
08:40:24 
08:40:24 Name:         nginx-cl-b
08:40:24 Namespace:    test-submariner
08:40:24 Labels:       <none>
08:40:24 Annotations:  <none>
08:40:24 API Version:  multicluster.x-k8s.io/v1alpha1
08:40:24 Kind:         ServiceExport
08:40:24 Metadata:
08:40:24   Creation Timestamp:  2020-12-22T06:39:31Z
08:40:24   Generation:          1
08:40:24   Resource Version:    25028079
08:40:24   Self Link:           /apis/multicluster.x-k8s.io/v1alpha1/namespaces/test-submariner/serviceexports/nginx-cl-b
08:40:24   UID:                 a84ba48e-9ef1-4d69-9a65-c89548007d15
08:40:24 Status:
08:40:24   Conditions:
08:40:24     Last Transition Time:  2020-12-22T06:38:32Z
08:40:24     Message:               Awaiting sync of the ServiceImport to the broker
08:40:24     Reason:                AwaitingSync
08:40:24     Status:                False
08:40:24     Type:                  Valid
08:40:24     Last Transition Time:  2020-12-22T06:38:32Z
08:40:24     Message:               Service was successfully synced to the broker
08:40:24     Reason:                
08:40:24     Status:                True
08:40:24     Type:                  Valid
08:40:24 Events:                    <none>
```

**Comment by aswinsuryan** [comment] 2020-12-22 14:32
> 020-12-22T06:39:31Z"

Oh ok , but lighthouse/submarienr  does not have any role in reporting this. The creation timestamp is populated by Kubernetes and I think the age should be derived from it while we query. So this could be related to some issue kube-apiserver, like it got too busy or another issue.

**Closed** 2020-12-23 06:13 UTC
Labels: enhancement, service-discovery
